### ISSUE TITLE
Unrevealed addresses need to be revealed

### ISSUE THREAD

**Issue by habanoz** [tezos-reward-distributor-organization/tezos-reward-distributor#11]
**Is your feature request related to a problem? Please describe.**
Some users are not that before using an address for transactions it needs to be revealed. Users should be made aware.

**Describe the solution you'd like**
The application may check and instruct users to run reveal operation. 

**Describe alternatives you've considered**
The application may transparently run reveal command, but it is better if users do it with awareness.

**Comment by habanoz** [comment]
tzscan api is used for revelation check. An rpc based solution could not be found. 

Closing but suggestions are welcome.

**Comment by vkresch** [comment]
I will open a PR for this like discussed in #422.
