### ISSUE TITLE
insufficient funds

### ISSUE THREAD

**Issue by goodpen** [tezos-reward-distributor-organization/tezos-reward-distributor#116]
if you dont have enough tezos on balance to pay you received hash https://tzstats.com/operation/ooujFHaXQecd24mEa6Eikk8hMz6eqoLydxNnYBUhmpj3C4yNdX7

but operation faild, maybe TDR must warring about this (dont enough found to pay)

**Comment by jdsika** [comment]
@amzid I would classify it a bug if the funds are not checked before forging an operation - what do you think?

**Comment by habanoz** [comment]
Run_operation is supposed to fail if funds are not enough. 

Are you able to replicate the situation?

**Comment by goodpen** [comment]
> Run_operation is supposed to fail if funds are not enough.
> 
> Are you able to replicate the situation?
> 
> Do you have logs ?

in next cycle i replicate the situation and share log

**Comment by goodpen** [comment]
payment wallet not enough xtz but give me hash ongMAfRM4FvsCgzbpSRAyu4N66xBqaDEQ4zLtUrsLirUJov4vEt

log in attach 
[log.txt](https://github.com/habanoz/tezos-reward-distributor/files/3775572/log.txt)

**Comment by amzid** [comment]
This issue was reformulated in #220 and is solved by #251. Feel free to reopen the issue if needed.
