### ISSUE TITLE
Multiple instance support

### ISSUE THREAD

**Issue by habanoz** [tezos-reward-distributor-organization/tezos-reward-distributor#15]
**Is your feature request related to a problem? Please describe.**
Multiple instance support needed
 
**Describe the solution you'd like**
structure config directories according to baking address so that multiple instances can run simultaneously.

**Comment by habanoz** [comment]
@jdsika @utdrmac 

This is an old feature. If implemented, a single TRD installation will be able to manage reward payouts for multiple bakers. 

I am not sure whether this will help anyone. What do you think?

**Comment by utdrmac** [comment]
I think that if you really need to run two TRD's, just launch two python3 commands and pass configdir and reportsdir to different locations.

```
mkdir ~/trd/baker1/
mkdir ~/trd/baker2/

python3 src/main.py -f ~/trd/baker1/cfg -r ~/trd/baker1/reports ....
python3 src/main.py -f ~/trd/baker2/cfg -r ~/trd/baker2/reports ....
```

**Comment by habanoz** [comment]
Let's leave this feature until someone claims it necessary.

Closing.

**Comment by jdsika** [comment]
@habanoz can you create a section in the documentation explaining how to run multiple instances. Then the information on how to solve this persists
