### ISSUE TITLE
Feature Request: Self Bonded Delegator Payout

### ISSUE THREAD

**Issue by gaia** [tezos-reward-distributor-organization/tezos-reward-distributor#155]
Is it currently possible to calculate rewards for a delegator that deposited their full stake in the baker, and is charged 0% for baking? Their reward would be added to their initial stake and keep on baking at 0%.

**Comment by utdrmac** [comment]
Isn't this considered an "owner" or "founder"?
I know that in the "specials", you can put a delegator at 0% fee. But I think that if they  transfered to baker rather than delegate, they become owner/founder/supporter. One of those.

**Comment by gaia** [comment]
yep, I'd think it is an owner or founder with 0% rights to any rewards outside their own initial investment, compounded. Would this be an owner or founder?

**Comment by utdrmac** [comment]
Reading this,  https://github.com/habanoz/tezos-reward-distributor/blob/master/docs/configuration.rst, I think you need owner?

**Comment by gaia** [comment]
What confuses me is "This map is optional if owners do not want to be paid for baking rewards, in this case, service fee remains in baking balance."

The owner wants to be paid the baking rewards accrued from the the amount they own, and the rewards should be added to their balance.

"in this case, service fee remains in baking balance." I'm not sure why "service fee" is used here: founders get a share of service fees. It should read "This map is optional if owners do not want to be paid for baking rewards, in this case, _baking rewards_ remains in baking balance."

If it should read  _baking rewards_ above instead of _service fee_ , then I need to setup an owner address and ratio. But their ratio will change on every cycle, whether or not they are withdrawing their rewards.

I believe that if this functionality already exists, it needs further clarification.

**Comment by dansan566** [comment]
I think it is only possible to get this information if founders_map and owners_map have the same ratios. Let's assume you have one owner and one founder:
founders_map : {'tz12345' : 1.0}
owners_map : {'tz12345' : 1.0}
rules_map:
  tz12345: TOB
In calculations CSV you would see how much this address would receive from baking (owners_map) and from the service fee (founders_map).
This issue is probably also connected to #103 ! The spelling mistake will be fixed with #302

**Comment by jdsika** [comment]
@dansan566 is further improvement of the documentation needed for the v8.5 release? If not close the issue and if yes please do it in the upcoming PR for the release preparation

**Comment by jdsika** [comment]
@dansan566 please check if #370 solves this and mention it for auto close

**Comment by dansan566** [comment]
@jdsika can be closed, already solved.
