### ISSUE TITLE
How ratios are calculated - founders/Owners 

### ISSUE THREAD

**Issue by Z1Quest** [tezos-reward-distributor-organization/tezos-reward-distributor#169]
from the docs ' Each item in this dictionary represents PKH of each balance owner and his ratio of the amount he owned in the total baking balance'

Where the balance amount is captured from? evaluated balance? 

is it possible to set a flag to pay some founders/owners but not all? calculation is mandatory each cycle.

thanks

**Comment by utdrmac** [comment]
The balance for founder is captured just like any other delegate. You can set specific PKH to be ignored (set 'to balance') in the config.yaml or using the configurator.py script.

**Comment by Z1Quest** [comment]
If you have 5 owners with different contributions, how their ratio is calculated? All tokens in TZ1 bakery address.

**Comment by utdrmac** [comment]
You configure their ratios manually in your .yaml file. This allows you to give different ratio to different owners based on whatever you want.

**Comment by Z1Quest** [comment]
Appreciate your answers, but ratio based on what balance?  total staking balance, evaluated balance? thx

On Dec 30, 2019, at 5:11 PM, Matthew <notifications@github.com> wrote:

﻿

You configure their ratios manually in your .yaml file. This allows you to give different ratio to different owners based on whatever you want.

**Comment by utdrmac** [comment]
Not based on any balance. Completely static calculation, AFAIK.

**Comment by Z1Quest** [comment]
from the the docs:

owners_map : A dictionary of PKH and ratio ( decimal in the range [0-1]) pairs. Each item in this dictionary represents PKH of each balance owner and` his ratio of the amount he owned in the total baking balance`.

**Comment by utdrmac** [comment]
Correct, "amount he owned in the total". "owned" past tense. How much he owned in his balance before transferring to the master tz1.

**Comment by Z1Quest** [comment]
Ok! if this scenario is not possible, is there any other method to calculate the owners ratio?

**Comment by utdrmac** [comment]
Think of "owners" like any other business investment. Bob, Alice, Charles all join together with Dave. Bob gives $10, Alice $40, Charles $5, and Dave started the company with $100. Dave has agreements with each that they will receive a % return on their investment. This % doesn't change. It's always the same rate. $155 is the total in the business. Whenever there is profit, Dave gets 64.5%, Alice 25.8%, Bob 6.5%, Charles 3.22%. In a normal business, these ratios don't change based on how much is in each's bank account. Each pay period, the % reward for each member is transfered to their personal account. It is not typically added back to the company's balance. If it was, then all of the agreements would have to be recalculated each time, but that changes the agreements. What if Alice does NOT want her profits to go back in to the company but Bob and Charles do? Alice has an agreement that she always get's 25.8%. But if Bob/Charles put in more, then Alice's % would decrease. That may not be what Alice agreed to and she may leave.
Thus, owners is always a static calculation and not based on any individual balance.

**Comment by zcryptox** [comment]
Thanks for the detailed response. the static calculation makes it clear how TRD works. Is there a way to calculate statically and distribute service fees/rewards for only one owner while others retain their rewards in the bond pool?

**Comment by utdrmac** [comment]
You should be able to configure any address as 'TOB' (to balance) and any rewards will be left in the bond pool tz1 balance.

**Comment by Z1Quest** [comment]
to confirm, PKH address in owners_map should be added to rules_map section with TOB for rewards not to be sent out?

**Comment by utdrmac** [comment]
Correct. Be sure to use `-V -D` to test the next cycle payment and read all of the output actions in `log/app.log` to confirm.

**Comment by Z1Quest** [comment]
thanks. made the changes and ran it with -v -d 
the PKH address line (Owners) in the log showing 1 for payable field? although it is excluded in configuration? will it be superseded by the exclusion to pay?

**Comment by utdrmac** [comment]
Not sure. I've never tested this config before. I'd say that since the person you are paying is an owner, and you know them, any funds accidentally sent can be sent back without fuss ;-)
