### ISSUE TITLE
Custom Tezos client path

### ISSUE THREAD

**Issue by denver-s** [tezos-reward-distributor-organization/tezos-reward-distributor#171]
**Is your feature request related to a problem? Please describe.**
I cannot select a custom path for the client dir (the "base-dir" argument used by tezos-client executable) where public keys are stored (usually ".tezos-client" in user dir).

**Describe the solution you'd like**
A similar argument like "executable-dirs".

**Comment by jdsika** [comment]
This will not be necessary after #209

**Comment by utdrmac** [comment]
@denver-s Is this still an issue? You can customize tezos-client's config by using `~/.tezos-client/config.json` and put the base-dir in the config.
