### ISSUE TITLE
Gracefully handle 5XX errors

### ISSUE THREAD

**Issue by utdrmac** [tezos-reward-distributor-organization/tezos-reward-distributor#173]
**Describe the bug**
TRD does not handle 5XX errors from http RPC endpoints well.

**To Reproduce**
Use a public RPC endpoint that is currently down/offline but still returns 522 or 524. As of right now, https://rpc.tulip.tools/mainnet/chains/main/blocks/head, is returning CloudFlare 522 errors.

**Expected behavior**
A proper error message be displayed, not a stack-trace/Exception

```
Traceback (most recent call last):
  File "src/pay/payment_producer.py", line 225, in try_to_pay
    reward_model = self.reward_api.get_rewards_for_cycle_map(pymnt_cycle)
  File "src/rpc/rpc_reward_api.py", line 45, in get_rewards_for_cycle_map
    current_level, current_cycle = self.__get_current_level()
  File "src/rpc/rpc_reward_api.py", line 123, in __get_current_level
    def __get_current_level(self):
  File "src/rpc/rpc_reward_api.py", line 115, in do_rpc_request
    if resp.status_code != 200:
Exception: Request 'https://rpc.tulip.tools/mainnet//chains/main/blocks/head failed with status code 524
```

**Comment by jdsika** [comment]
This seems to be a small fix and quick win. Will you fix this for the next release? @utdrmac
