### ISSUE TITLE
Partial missing payments to delegators

### ISSUE THREAD

**Issue by Michshelle** [tezos-reward-distributor-organization/tezos-reward-distributor#182]
**Describe the bug**
I found the reward payment process for cycle 183 had some issue.  The payment account paid to most of my delegators but ignored a few.  
After checking the done/fail/calculation folders, it can be confirmed the problem started during the calculation process.  
The ignored accounts were not shown in the 183.csv in the calculation folder.

Relevant links:
Baker: https://tzstats.com/tz1dhwJY5B1jKdkF7zcyu1v6EBEQjpGmAp1E
Missed account 1: https://baking-bad.org/KT1P6fCRqMmnfVRXh4EMEkx3vmatJyS3dwtg
Missed account 2: https://baking-bad.org/KT1TLpHzkPCGwPjfLmqCs1iVqmvtBLmLAv9Y

**To Reproduce**
It was the first time I encountered such issue.  I don't know how to reproduce the case.  The subsequent cycle payments look fine.

**Expected behavior**
Pass

**Screenshots**
183.csv in calculation folder (FYI, may able to be utilized to do some comparison with the Rewards tab on tzstats)

**Environment**
 - Source Code Build 
 - Chain mainnet
 - actual command used, at that time it was `python  src/main.py -E ~/docker_mainnet/tezos -P prpc --node_addr 136.243.240.44:443`  It was under "run and forget", so the cmd could be typed during previous cycles.  Honestly, I cannot recall the exact time point.
Starting from cycle 185, I've switched to `python src/main.py -E ~/docker_mainnet/tezos -P rpc --node_addr 127.0.0.1:15000`, as soon as the local archive node got synced.

**Additional context**
Pass

**Comment by Michshelle** [comment]
183.csv
`address,type,balance,ratio,fee_ratio,amount,fee_amount,fee_rate,payable,skipped,atphase,desc,payment_address
tz1dhwJY5B1jKdkF7zcyu1v6EBEQjpGmAp1E,B,278896747302,1.000000,0.000000,153286111.000000,0.000000,0.000000,0,0,-1,Baker,None
tz1MVf5PX1rKmH3fMXHGUKjcuWHUgt3dWjDp,D,115859653425,0.4157452507,0.0000000000,63727973.000000,0.000000,0.000000,1,0,-1,None,tz1MVf5PX1rKmH3fMXHGUKjcuWHUgt3dWjDp
tz1V6gs1CSZD49HB9yANkAA8pBJ79oSGiXMq,D,20600586235,0.0705956632,0.0033264972,10821335.000000,509906.000000,0.045000,1,0,-1,None,tz1V6gs1CSZD49HB9yANkAA8pBJ79oSGiXMq
tz1LEZT5a3kEBr2ahbuFx88xp4bXpkQJ7jBK,D,18411341661,0.0630933926,0.0029729871,9671341.000000,455718.000000,0.045000,1,0,-1,None,tz1LEZT5a3kEBr2ahbuFx88xp4bXpkQJ7jBK
tz1YvE23HCvxMNPqWsgQyYMw8Rm2UeMnPCMs,D,9987656557,0.0342264648,0.0016127654,5246442.000000,247215.000000,0.045000,1,0,-1,None,tz1YvE23HCvxMNPqWsgQyYMw8Rm2UeMnPCMs
tz1XVmEX7uiTq21QYiLyaD97MLP92mXbexwi,D,7000996231,0.0239915489,0.0011304918,3677571.000000,173289.000000,0.045000,1,0,-1,None,tz1XVmEX7uiTq21QYiLyaD97MLP92mXbexwi
tz1Mnvr7uHi1aPJrVcr1bpzJST9rfK5yqmSq,D,5999997280,0.0205612492,0.0009688547,3151754.000000,148512.000000,0.045000,1,0,-1,None,tz1Mnvr7uHi1aPJrVcr1bpzJST9rfK5yqmSq
tz1YD69fg73bgpXHpAxSMYeQD2YtQ6Yo8zW2,D,5180266616,0.0177521335,0.0008364880,2721156.000000,128222.000000,0.045000,1,0,-1,None,tz1YD69fg73bgpXHpAxSMYeQD2YtQ6Yo8zW2
KT1HbxrvPTXMQSvg9YSNBxAvkk25N6JjyAQK,D,5069471679,0.0173724530,0.0008185973,2662956.000000,125480.000000,0.045000,1,0,-1,None,KT1HbxrvPTXMQSvg9YSNBxAvkk25N6JjyAQK
tz1Kk5UaQk3CY7VwiKmKQDrT1CZfFWiyndV1,D,3967479931,0.0135960634,0.0006406522,2084088.000000,98203.000000,0.045000,1,0,-1,None,tz1Kk5UaQk3CY7VwiKmKQDrT1CZfFWiyndV1
tz1QhY9BVCuGcRgCfgLwUwV24Jwsrdg5DPk5,D,672493731,0.0023045529,0.0001085915,353256.000000,16646.000000,0.045000,1,0,-1,None,tz1QhY9BVCuGcRgCfgLwUwV24Jwsrdg5DPk5
KT1VK9oWfo2STjmrYcGuCHZ8VARnSNtaLLpP,D,607685008,0.0020824614,0.0000981265,319212.000000,15041.000000,0.045000,1,0,-1,None,KT1VK9oWfo2STjmrYcGuCHZ8VARnSNtaLLpP
KT1Ve5QPmaq8kiu46BcaAkXwR9pUZ2H2zLhK,D,525160158,0.0017996590,0.0000848007,275863.000000,12999.000000,0.045000,1,0,-1,None,KT1Ve5QPmaq8kiu46BcaAkXwR9pUZ2H2zLhK
tz1PDtnEq2MGSBQYKJgQaFCUuc2YLabZDpHh,D,214464710,0.0007689753,0.0000000000,0.000000,0.000000,0.000000,0,1,1,Excluded by min delegation,tz1PDtnEq2MGSBQYKJgQaFCUuc2YLabZDpHh
tz1Q5tmJDMpEAohupSyeRKmYQxgz8nTwtwM4,D,2554280,0.0000091585,0.0000000000,0.000000,0.000000,0.000000,0,1,1,Excluded by min delegation,tz1Q5tmJDMpEAohupSyeRKmYQxgz8nTwtwM4
tz1QAgVwUxSZcnhBsKyHs5rSFASn3kqdPspD,D,283842,0.0000010177,0.0000000000,0.000000,0.000000,0.000000,0,1,1,Excluded by min delegation,tz1QAgVwUxSZcnhBsKyHs5rSFASn3kqdPspD
KT1EXhSTPPpDyHUvUehfhdx4b5m9RxHY1FW3,D,5000,0.0000000179,0.0000000000,0.000000,0.000000,0.000000,0,1,1,Excluded by min delegation,KT1EXhSTPPpDyHUvUehfhdx4b5m9RxHY1FW3
KT1Ez8bTsUbhpyc4jx9nML9V7EmhCXWLdZmk,D,0,0.0000000000,0.0000000000,0.000000,0.000000,0.000000,0,1,1,Excluded by min delegation,KT1Ez8bTsUbhpyc4jx9nML9V7EmhCXWLdZmk
KT1USu3e1ur66GQnVXzcgVnXeUXLqThmESCn,D,0,0.0000000000,0.0000000000,0.000000,0.000000,0.000000,0,1,1,Excluded by min delegation,KT1USu3e1ur66GQnVXzcgVnXeUXLqThmESCn
OWNERS_PARENT,OWNERS_PARENT,84796650958,0.3042802552,0.0000000000,46641937.000000,0.000000,0.000000,0,0,-1,None,OWNERS_PARENT
FOUNDERS_PARENT,FOUNDERS_PARENT,0,0.0125988522,0.0000000000,1931229.000000,0.000000,0.000000,0,0,-1,None,FOUNDERS_PARENT`

**Comment by jdsika** [comment]
I guess it is an issue with specific account balance requests which are not gracefully handled by the public node. This should be fixed by now but the logging should be clear as well. Was it the problem with the Tezos Ukraine node @amzid ?

**Comment by jdsika** [comment]
@Michshelle what node was it that you were using? I do not know the IP address. Did it occur again?

**Comment by Michshelle** [comment]
No, the issue was not persistent.  It worked well afterwards.

**Comment by jdsika** [comment]
@amzid I would like to have a confirmation that a failure in single rpc requests is handled gracefully and retried. Or do you think the issue was of different nature?

**Comment by jdsika** [comment]
I suspect a duplicate to #321 and will close this one. @amzid please reopen if you think it is due to a different reason then a retry of the failed rpc call
