### ISSUE TITLE
TF Grant Submission

### ISSUE THREAD

**Issue by utdrmac** [tezos-reward-distributor-organization/tezos-reward-distributor#188]
Hello @habanoz , @amzid , @jdsika ,
I think it's fair to say that TRD is one of the, if not the, most used rewards payments system for Tezos. This project/tool should have TF grant funding behind it. If TF can give a grant to a for-profit company, they can give one here.
I'll be submitting the grant request later this week. I do not plan to request the max amount; probably somewhere around 40% of the max. Any funds that I acquire from the grant I plan on distributing to TRD code contributors and documentation writers as we all deserve compensation for our time in making this tool what it is today.

**Comment by jdsika** [comment]
If you submit a grant then only for new features of the tool. 
* Support for the protocol upgrades in 2020
* Extension of the documentation
* Monitoring for the run and forget mode

**Comment by dansan566** [comment]
I also think it's a good idea to ask for a grant. Especially @habanoz , @amzid and you have already spent so much time on this that this is only justified that further workload will be compensated in the future. 

However, I have to agree with @jdsika that a grant may only be used for future development and features. It would also provide an incentive to do so. I would like to hear the opinion of @habanoz - as far as I am informed a request was rejected at that time.

**Comment by habanoz** [comment]
I am sharing my past conversation with Tezos Foundation. It was not a private chat thus I believe it is appropriate to share.

**Comment by habanoz** [comment]
Dear Huseyin,

Thank you for applying for a grant from the Tezos Foundation. As you know, we receive a significant number of strong proposals. After conducting a full review of your project, the Foundation has decided not to fund your project at this time.

We sincerely value your efforts as a member of the community and hope that you will continue to be involved in the Tezos project. We appreciate your patience as your proposal was evaluated, and wish you the best of luck going forward.

All the best,
Charlie Wiser

**Comment by habanoz** [comment]
Dear Charlie, 

Thanks for your response. I will continue being a member of the tezos community.

As an ICO investor an active community member I need to understand why the proposal is rejected. I need to know that because I need to see that the foundation is doing wisely while vesting the money we devoted to project success. I also need to see that the foundation is doing wisely while appreciating the effort put to project success. 

I know that my proposal fills a gap in tezos ecosystem. It is not a concept but a working product. I receive emails from bakers presenting their pleasure and gratitude. I put a lot of effort to build it. With respect, I doubt that proposals are evaluated decently. I can see that the video I uploaded is not watched at all. 

Could you be kind enough to share the criteria my proposal failed to satisfy? 

Thanks
Best Regards

**Comment by habanoz** [comment]
Hi Hüseyin,

Thanks for your response. I'm happy to provide a more detailed explanation as to why your proposal was not approved.

The primary reason why your proposal was not approved is that the Tezos Foundation has already issued several grants towards projects that have released products for handling baking rewards payouts. Cryptium Labs and TezosRio are two grantees that have released products like the one you proposed a grant for, and zednode, another grantee, will soon release a similar product for bakers. Furthermore, there are other community members who have released baking rewards payout tools, such as Figment Networks.

As a good amount of funds have already been issued for the development of baking rewards payout tools, the Foundation does not see this area as a current priority for grantmaking efforts.

I hope that this explanation helps to provide some clarity about the decision. Please let me know if you have any further questions.

All the best,
Charlie

**Comment by habanoz** [comment]
Thanks for explanations.

Regards

**Comment by habanoz** [comment]
You're welcome. Please let me know if you have any questions in the future. Very much appreciate your involvement in the Tezos project and look forward to the things the community and ecosystem will accomplish in the future.

Sincerely,
Charlie

**Comment by habanoz** [comment]
That was the whole conversation.  

--

A new proposal can be made. If it succeeds, granted money should be used for future developments and maintenance. Even though I made a lot of effort to build the software I do not demand any shares from the grant, except for my future contributions. 

The money should be managed by a community member, whom my be called the custodian. I nominate @jdsika for this responsibility. Of course this responsibility should be compensated as well. 

The custodian should pay for the efforts fairly. 

Any future development that is eligible for payment should be regarded as a need for the community. For this purpose, a GitHub issue should be created and community members should discuss the necessity. If a consensus to implement a future is reached then it can be built and paid afterwards.

**Comment by goodpen** [comment]
Most all bakers use TDR, but grand received another projects, something wrong with that

**Comment by utdrmac** [comment]
I'm drafting the proposal on google drive and will share it here for comments/feedback before submission.

**Comment by zcryptox** [comment]
It seems TF is not qualifying projects grants based on code quality/usability/etc… these are the reasons why most bakers use TRD. 
We tried the other reward distribution software mentioned in the TF reply, no one of them is a match to TRD but built with TF Grants to serve large bakers only :) - go figure where our ICO $ are being spent!  

Their approach to grants is autocratic, primarily the reason behind the fork of Dune Network.

**Comment by utdrmac** [comment]
In reading TF's reply above, what has "TezosRio" contributed as far as handling rewards payouts?

zednode has GingerBread but that appears to be a dead project. Demo site doesn't work and last github commit was April 2019.

Cryptium Labs has Bakerie, but it's not anywhere near as feature rich as TRD. Additionally, it doesn't calculate real payouts; it uses idealized payout amounts.

Figment Networks' tool doesn't work as far as I can tell. I attempted to use it for a handful of missed payments, but you still must make all the calculations yourself.

**Comment by dansan566** [comment]
@utdrmac they contributed tabs: https://github.com/TezosRio/taps 
I would put it in the same league as Bäckerei from CL.

**Comment by utdrmac** [comment]
https://docs.google.com/document/d/1jH-6k97J3tSkrZ1dlgbIClT0egnoJFz3sXKyX3AMGsY/edit?usp=sharing

Please comment on the doc itself; everyone should have comment ability.

**Comment by jdsika** [comment]
> 
> 
> That was the whole conversation.
> 
> --
> 
> A new proposal can be made. If it succeeds, granted money should be used for future developments and maintenance. Even though I made a lot of effort to build the software I do not demand any shares from the grant, except for my future contributions.
> 
> The money should be managed by a community member, whom my be called the custodian. I nominate @jdsika for this responsibility. Of course this responsibility should be compensated as well.
> 
> The custodian should pay for the efforts fairly.
> 
> Any future development that is eligible for payment should be regarded as a need for the community. For this purpose, a GitHub issue should be created and community members should discuss the necessity. If a consensus to implement a future is reached then it can be built and paid afterwards.

@habanoz I proposed to have two custodians with a multisig wallet. We will create a PR template that let's the creator evaluate his own contribution in terms of "effort spent" + their XTZ address. There will be a technical review, when the technical review is fnished the custodians will agree on a price for the contribution. The XTZ will be payed out and the transaction will be added to the PR when it is merged.

**Comment by habanoz** [comment]
@jdsika I like the idea, having two custodians would be better. However, selecting a second custodian is not an easy task. 

Let's assume, a developer is both custodian and PR creator. It would be a conflict of interest to let a developer decide payment amount. 

IMHO, If there is going to be a second custodian, he should have technical skills enough to make technical review, but should not expect any payments if he happens to contribute to the code. 

What is your opinion?

**Comment by dansan566** [comment]
@habanoz, In my opinion, it should be a multi-sig-wallet where you, @jdsika and the TF have the keys. There is a 2/3 threshold - meaning that two of the keyholders have to agree (you and @jdsika). The TF is a backup in case one of you has an accident.  I don't see a conflict of interest here because the four-eyes principle is applied.

**Comment by utdrmac** [comment]
Hey everyone. We have about 1 more week before the grant cutoff. Is there anything else we need to add to the doc? Who will be submitting the actual form on TF website? Who should be the main contact point for the grant process?

**Comment by jdsika** [comment]
No past contributions. I would reject the proposal myself with that mentioned. I will review it tomorrow, please contribute as much as possible today. I also think @habanoz should hand in the proposal. Thursday morning we have to sign and send the proposal around by email.

**Comment by utdrmac** [comment]
@habanoz All mentions of previous work have been removed from the grant doc.

**Comment by utdrmac** [comment]
@jdsika Are we all going to sign within the google doc, or should I "print to PDF" and email it around? Or use something like docusign?

**Comment by utdrmac** [comment]
@habanoz @jdsika @amzid 
I have the doc as a PDF and uploaded to docusign, but I need emails to send it through docusign. Can you please ping me in Telegram or bakers-slack with your email? Or add it to the google doc under your signature line?

**Comment by habanoz** [comment]
@utdrmac 

I do not have your slack or telegram id. Would you mind sharing? No link to docusign either.

My email address is :
huseyinabanox@gmail.com

Regards

**Comment by utdrmac** [comment]
@habanoz I sent my email to @jdsika Docusign won't let you just link to a document, as far as I can tell. You have to add recipients via email for them to sign.

**Comment by utdrmac** [comment]
Grant has been submitted to TF! Will continue to put updates here unless someone wants to start a Telegram group or join #trd in the baker Slack channel.

**Comment by habanoz** [comment]
Thanks. For the good of transparency, let's continue over this thread.

**Comment by utdrmac** [comment]
If anyone talks to TF people, gently remind them that they have given grants to for-profit companies in the past, which we are not. I was thinking about that this morning, how TF has given money to profitable companies, but not to this open-source, not-a-company, project.

**Comment by jdsika** [comment]
I would like to change the license to apache 2.0 if all contributors agree?

**Comment by utdrmac** [comment]
What's the benefit/reasoning behind changing to apache 2.0? (I don't  know much about all the different licensing models. EILI5 please)

**Comment by jdsika** [comment]
There are quite a few differences and we could talk about this for days but the most relevant difference is the "copy left" effect. If you include any work from a GPL3 licensed work somewhere else it would be a "derived work" which means that you have to put it under GPL3 again. It "infects" every other piece of code.
This is why a lot of projects chose non copy left licenses like MIT (Tezos) or lesser GPL, or Apache 2.0 (conseiljs). In contrary to MIT the Apache license is more verbose and talks about patents and lots of other stuff. It is the "license of choice" for the integration of open source software in a BMW e.g. (there are tons of licenses you can use and all are evaluated by itself but this is favorite pick).

**Comment by habanoz** [comment]
I have to disagree. 

From open source perspective, I believe TRD should be left open sourced forever. All modified versions should be left open sourced as well. I just do not like the idea of someone copying and closing the code then rebranding it to sth else. 

From licensing perspective, GPL3 enforces that derivative work should be released in GPL3 as well. In that manner I believe it does not allow moving from GPLv3 to other licenses e.g. Apache 2.0.

All contributions can be made under Apache 2.0. However, I believe TRD as a software should continue its life under GPLv3.

**Comment by jdsika** [comment]
As "owner" you can relicense that's why asked if all contributors would agree to "...". The current state is and will always be also available under gpl then.
Consider the following case:
You want to offer a custom export for your client. That would require as "plug-in" that needs specific knowledge of tax and accounting for a country. If you would integrate a mechanism to load plugins then you could not leave those plugins closed source as the gpl would infect them. I guess the only way of interaction might be through files or different processes accessing a common database. Gpl just always gives headache - sure we can live with it. I just want to open the discussion on it. E.g. conseil was unusable under gpl as it is something to be included as interface into other programs. Then it would infect everything. That's why they changed to apache

**Comment by habanoz** [comment]
An Apache 2.0 cannot include GPLv3 code. However, GPLv3 code can include Apache 2.0 code. 

Considering the example case, I am not expert, but believe it should be possible to develop and license the "plug-in" externally. You gave one example. Another could be that, the host application , TRD in our case, automatically loads plugins without a direct link which makes the application and the plugin completely decoupled. This feature was among planned developments but I did not find chance to develop.

For libraries it is an obvious problem to choose copyleft licenses. For applications I believe it is more convenient to choose copyleft licenses.

**Comment by utdrmac** [comment]
Any updates from the foundation? Did we get rejected? Do they want more information?

**Comment by jdsika** [comment]
I forgot who handed in the grant proposal haha

**Comment by utdrmac** [comment]
I submitted it. I have not heard anything at all. Total silence. If someone has a contact at TF, maybe ping them for update?

**Comment by jdsika** [comment]
I think noone has gotten a reply yet- just wait
