### ISSUE TITLE
Evenly distribute payments after the end of the cycle

### ISSUE THREAD

**Issue by sergattic** [tezos-reward-distributor-organization/tezos-reward-distributor#194]
**The spike of payouts**
If TRD is running as daemon, it starts sending rewards immediately after cycle finish. 
As we noticed, many of bakers trust TRD to perform automatic payments -  it cause the spike of transactions in the same time. A limited number of transaction could be processed per block.   Tezos nodes are queueing pending transaction, causing significant performance degradation: response time increase in 200k times (from 0.001 sec to 180-200 sec). Performance degradations leads to public network congestion. 

**http request timeouts** 
Tezos public nodes could not expose RPC service, without http balancer protection, but usually http request should not exceed 60 seconds without transfer activity. For example CloudFlare breaks http connection after 120s of inactivity. 

**Solution**

1. Wait 100-200 blocks after cycle finish, before performing payouts in daemon mode. Give ability to perform payment of older versions.  
2. Wait for number of blocks, which is equal to number of rolls. This way small bakers will be served first, larger baker will be delayed for 20-30 minutes (1200 - 1800 rolls/seconds). 
Nobody will care about 10-45 minutes of delay. 

**Dedicated TRD host**
I understand, that some part of TRD setup will continue to perform payments immediately after each cycle.  In order to server such request, we (tezos.org.ua public node) planned to create dedicate endpoint for TRD with:
1.  extremely high https timeouts (5-10 minutes)
2. Do not use CloudFlare as ddos screen
3. Limit number of connection per IP in order to protect host from long connection type to dos attacks 

**Proof of Spike**
[Network Traffic increase 25x during TRD payouts ](https://monitor-net.tezos.org.ua/d/hb7fSE0Zz/monitor-net-tezos-org-ua?orgId=1&from=1579968963960&to=1580141763961&var-job=tezos_org_ua_exporter&var-hostname=All&var-node=All&var-maxmount=%2Fmnt%2Foperational&var-env=&var-name=&panelId=157&fullscreen)

**Comment by utdrmac** [comment]
I don't think such an extreme solution of needing a dedicated TRD endpoint is necessary. CloudFlare should have a setting that allows TRD users to pass a specific header which "authorizes" these requests and backs off on the ddos protection.

I like the idea of, by default, waiting for "number of blocks equal to 1/2 the number of rolls".

**Comment by sergattic** [comment]
Trd is open-source, if attacker will know "secret" header, he could open 10k connection and overflow connection pool. 
In any case, we can not lean on CF, because its central point of failure, which is unacceptable for our "decentralized brains" :) 
Making dedicated host is just +1 config file in our nginx , so we are happy to make such experiment. 
The only thing, we'll have some expenses to obtain wildcard cert , buy new ips, install more balancers - it could take some time.

**Comment by utdrmac** [comment]
Knowing "secret" header is no different than knowing "secret dedicated host".

**Comment by jdsika** [comment]
It is important to find a solution that also protects the node provider. 
* Restricting requests from single IPs could be part of it?
* Allowing a signed commit/release of TRD?
* @royscheeren do you have ideas out of experience ?

**Comment by sergattic** [comment]
- Restricting requests from single IPs is some measure, but will not protect from DDOS
- validating signature from baker could be most efficient solution. 

BTW, 
1. mainnet.tezos.org.ua is already operating without CloudFlare with extream timeouts, should work fine even for request up to 360 sec. let see what will happen after next cycle, hope will not find other "surprises" 
2. trd.tezos.org.ua is also created, but not proper tested, will ping you after performing load/integration/unit test

**Comment by utdrmac** [comment]
Is this still an issue?

**Comment by sergattic** [comment]
Is still the issue , but GigaNode is able to handle because of increasing
capacity

пт, 24 июля 2020 г. в 18:51, Matthew <notifications@github.com>:

**Comment by utdrmac** [comment]
Since Delphi decreased the cost of transactions, and due to giganode's increased capacity, I believe this issue can be closed.
