### ISSUE TITLE
Feature Req: Transfer Bond to Payout Address

### ISSUE THREAD

**Issue by utdrmac** [tezos-reward-distributor-organization/tezos-reward-distributor#197]
From baker's slack (FreshTezos):

> When running TRD continuously and disbursing rewards from a separate wallet, has anyone found a method to programmatically top up the payout wallet?
> I still fire up TRD one payout at a time, first calculate the total, fund the payout wallet, then run it again to disburse funds.

This sounds like an easy to do feature request. Just like the actions above, after calculating reward total, execute a transfer from baker address to payout address. Wait for X confirmations, then resume payouts.

**Comment by gaia** [comment]
Freshtezos here. I started on a bash script to run hourly. Should be done tomorrow.

```
#!/bin/bash

# You need to install JQ: https://stedolan.github.io/jq/

balance=$(curl -s https://api.tzstats.com/explorer/account/tz1iXQ3rgNt3rNHt9iNTm2muQYg1Msw2faFq | jq -r '.total_balance')
balance=${balance%.*} # https://unix.stackexchange.com/a/316001/18568
cycle=$(curl -s https://api.tzstats.com/explorer/cycle/head | jq -r '.cycle') 
let cycle="$cycle - 6"
height=$(curl -s https://api.tzstats.com/explorer/tip | jq -r '.height')
end_height=$(curl -s https://api.tzstats.com/explorer/cycle/head | jq -r '.end_height') 
let blocks_to_end="$end_height - $height"

if [ $blocks_to_end -lt 3840 ]; then  # && current cycle hasn't been paid/check for cycle payout
	if [ $blocks_to_end -gt 768 ] && [ $balance -lt 10 ]; then
		# if cycle payout calc file is not present
		# run tpaycalc
		# if present, alert acct has not been funded
		echo "tzpaycalc $cycle"
	elif [ $blocks_to_end -le 768 ] && [ $balance -ge 10 ]; then
		# acct has been funded
		# check if paid out file is present
		# if not, payout	
		echo "tzpay $cycle"
	else 
		echo "alert: unfunded and unpaid"
	fi
fi
```

Problem in my setup is that funds are sent from the baker address, so I have to manually enter the password for the transfer (there is no signer for the baker's address, only for the payout wallet address, which remains at <1 XTZ at all times except a few minutes).

Ideally something similar would run in TRD, and alert the user every X minutes that they need to fund the payout wallet (and by how much), until the wallet is funded, when it then pays out the next time the routine is called.

**Comment by jdsika** [comment]
It is only possible if you do not use a ledger for baking?

**Comment by jdsika** [comment]
@gaia an email warning for insufficient funds has been added in #251 . As the TRD developers strongly recommend a secure setup with a ledger or similar I think the automatic payout from the baker address to the payout address is not a feature that can be implemented in a general way. We have to see if the introduction of the new accounts logic in the next protocol upgrade could change the situation. Until then I would consider this tpoic partially solved?

**Comment by utdrmac** [comment]
@gaia Can we close this? Now with the new plugins notifications, TRD will send you email/Twitter/Telegram/Webhook if your payout balance is too low or is near empty.

**Comment by gaia** [comment]
yes, thanks Matthew!
