### ISSUE TITLE
Feature Req: Reload baker yaml config without restarting

### ISSUE THREAD

**Issue by utdrmac** [tezos-reward-distributor-organization/tezos-reward-distributor#198]
Most linux services/daemons have the ability to reload a config file by sending SIGHUP or SIGUSR signals. If you make changes to the baker's .yaml file, you must restart the service/daemon to take affect. This FR is to add a simple 'reload' command to reprocess the yaml.

**Comment by jdsika** [comment]
I think this is a great improvement for the usability of the unatteneded mode. Please give an estimation if this feature can be implemented by you for the next release

**Comment by jdsika** [comment]
Be aware of #84 when coordinating this @habanoz and @utdrmac

**Comment by utdrmac** [comment]
Eh, I'm going back and forth on this one. A simple `systemctl restart trd` to load a new config shouldn't be that difficult. Most database systems require restarts for config changes, and even some standard applications. TRD should never be in a state where it is necessary to preserve that state on restart. Make a change to yaml file, restart TRD, TRD should "resume" right were it left off.

When we move to a DB-based config storage, we can reload the config right before a payouts cycle happens. Config changes would then always be applied to the next payments.

Close? or do you still want this?

**Comment by habanoz** [comment]
config file changes are not very likely. Restarting the service should not be a problem. My view is that auto-reload is nice to have but does not create much value. 

I recommend not to add.
