### ISSUE TITLE
Service is not working help!

### ISSUE THREAD

**Issue by logart89** [tezos-reward-distributor-organization/tezos-reward-distributor#208]
I updated with git pull

But my service is showing an error

`logart@logart2:~/code/tezos-reward-distributor$ sudo systemctl status tezos-reward.service
● tezos-reward.service - Tezos Reward Distribution Software
   Loaded: loaded (/home/logart/code/tezos-reward-distributor/tezos-reward.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-03-05 00:12:24 CST; 19s ago
     Docs: https://github.com/habanoz/tezos-reward-distributor
  Process: 2583 ExecStop=/usr/bin/python3 /home/logart/code/tezos-reward-distributor/src/stop.py (code=exited, status=0/SUCCESS)
 Main PID: 2608 (python3)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/tezos-reward.service
           └─2608 /usr/bin/python3 /home/logart/code/tezos-reward-distributor/src/main.py -s

Mar 05 00:12:27 logart2 python3[2608]:     batch = CsvPaymentFileParser().parse(payment_failed_report_file, cycle)
Mar 05 00:12:27 logart2 python3[2608]:   File "/home/logart/code/tezos-reward-distributor/src/util/csv_payment_file_parser.py", line 17, in pa
Mar 05 00:12:27 logart2 python3[2608]:     records = [self.FromPaymentCSVDictRow(row, cycle) for row in dict_rows]
Mar 05 00:12:27 logart2 python3[2608]:   File "/home/logart/code/tezos-reward-distributor/src/util/csv_payment_file_parser.py", line 17, in <l
Mar 05 00:12:27 logart2 python3[2608]:     records = [self.FromPaymentCSVDictRow(row, cycle) for row in dict_rows]
Mar 05 00:12:27 logart2 python3[2608]:   File "/home/logart/code/tezos-reward-distributor/src/util/csv_payment_file_parser.py", line 22, in Fr
Mar 05 00:12:27 logart2 python3[2608]:     rl = RewardLog(row["address"], row["type"], None)
Mar 05 00:12:27 logart2 python3[2608]: TypeError: __init__() missing 1 required positional argument: 'current_balance'
Mar 05 00:12:27 logart2 python3[2608]: 2020-03-05 00:12:27,449 - MainThread - Application start completed
Mar 05 00:12:27 logart2 python3[2608]: 2020-03-05 00:12:27,450 - MainThread - --------------------------------------------
`

Also used 

`python3 src/main.py -C 202 -D -P rpc -M 3 -V`

`2020-03-05 00:18:28,428 - producer  - Checking for pending payments : checking 202 <= 208 - (5 + 1) - 0
2020-03-05 00:18:28,428 - producer  - Payment cycle is 202
2020-03-05 00:18:28,654 - producer  - Error at payment producer loop, will try again.
Traceback (most recent call last):
  File "/home/logart/code/tezos-reward-distributor/src/pay/payment_producer.py", line 225, in try_to_pay
    reward_model = self.reward_api.get_rewards_for_cycle_map(pymnt_cycle)
  File "/home/logart/code/tezos-reward-distributor/src/rpc/rpc_reward_api.py", line 39, in get_rewards_for_cycle_map
    "delegators"] = self.__get_delegators_and_delgators_balances(cycle, current_level)
  File "/home/logart/code/tezos-reward-distributor/src/rpc/rpc_reward_api.py", line 123, in __get_delegators_and_delgators_balances
    hash_snapshot_block = self.__get_snapshot_block_hash(cycle, current_level)
  File "/home/logart/code/tezos-reward-distributor/src/rpc/rpc_reward_api.py", line 203, in __get_snapshot_block_hash
    chosen_snapshot = self.do_rpc_request(request)
  File "/home/logart/code/tezos-reward-distributor/src/rpc/rpc_reward_api.py", line 105, in do_rpc_request
    raise Exception("Request '{} failed with status code {}, after {}, unique request_id {}".format(request, resp.status_code, time_out, resp.headers['CF-RAY']))
  File "/usr/local/lib/python3.6/dist-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'cf-ray'
`

**Comment by chiptus** [comment]
I had a different error, but try updating tezos-client, fixed it for me

**Comment by logart89** [comment]
My tezos-client was not working either but i did `git checkout mainnet && git pull && make build-deps && eval $(opam env) && make clean && make`
And now my tezos-client is working properly. 

Still my issue with TRD remains.

**Comment by DaylightCulture** [comment]
Getting an unknown protocol error: upgraded to the newest protocol and have the correct hash for mainnet  063989441228b26244c885cd3508609fe256ae51




2020-03-05 08:52:21,552 - MainThread - Command failed, error is |Fatal error: unknown protocol version.
|
2020-03-05 08:52:22,012 - MainThread - Loading baking configuration file /home/user/pymnt/cfg/tz1XXXXXXXXXXXXXXX.yaml
2020-03-05 08:52:24,090 - MainThread - Command failed, error is |Fatal error: unknown protocol version.
|
Traceback (most recent call last):
  File "/home/user/tezos-reward-distributor/src/cli/wallet_client_manager.py", line 134, in __list_known_addresses_by_pkh
    AddressValidator("known_address").validate(pkh)
  File "/home/user/tezos-reward-distributor/src/util/address_validator.py", line 16, in validate
    "Incorrect input in {}, address({}) length must be {}".format(self.context, address, PKH_LENGHT))
Exception: Incorrect input in known_address, address(unknown protocol version.) length must be 36During handling of the above exception, another exception occurred:Traceback (most recent call last):
  File "src/main.py", line 217, in <module>
    main(args)
  File "src/main.py", line 99, in main
    parser.validate()
  File "/home/user/tezos-reward-distributor/src/config/yaml_baking_conf_parser.py", line 32, in validate
    self.validate_payment_address(conf_obj)
  File "/home/user/tezos-reward-distributor/src/config/yaml_baking_conf_parser.py", line 130, in validate_payment_address
    addr_obj = self.wllt_clnt_mngr.get_addr_dict_by_pkh(pymnt_addr)
  File "/home/user/tezos-reward-distributor/src/cli/wallet_client_manager.py", line 66, in get_addr_dict_by_pkh
    self.generate_address_dict()
  File "/home/user/tezos-reward-distributor/src/cli/wallet_client_manager.py", line 85, in generate_address_dict
    self.addr_dict_by_pkh = self.__list_known_addresses_by_pkh()
  File "/home/user/tezos-reward-distributor/src/cli/wallet_client_manager.py", line 136, in __list_known_addresses_by_pkh
    raise ClientException("Invalid response from client '{}'".format(response), e)
exception.client.ClientException: ("Invalid response from client 'Fatal error: unknown protocol version.\n'", Exception('Incorrect input in known_address, address(unknown protocol version.) length must be 36',))

**Comment by jdsika** [comment]
@amzid could you please check? "Command failed, error is |Fatal error: unknown protocol version."

**Comment by utdrmac** [comment]
Just want it documented that I'm running TRD as below and are having no issues at all.

```
$ python3 src/main.py -f ~/.trd/cfg/ -r ~/.trd/reports/ -N MAINNET -E ~/tezos/ -O 20 -M 3 -C 202 -P prpc -Ap https://mainnet.tezos.org.ua -V
```

**Comment by utdrmac** [comment]
@logart89 Your issue appears to be corrupted CSV files. Look inside ~/pymnt/reports/ and move everything out of there to a backup location, then try running again. TRD is trying to parse one of your recent reports, looking for past failures, and for whatever reason, it is unable to properly parse one of your files. Best solution is to move the CSV files out of their location, and run TRD again. When you run it, I suggest you run it manually (ie: not via service),  and specify `-C 202 -M 3 -V -D` to check that all is well first.  Then run payments manually by removing the `-D`.

**Comment by utdrmac** [comment]
@DaylightCulture Just because you have the correct checkout hash does not mean you are running the correct binaries. Please confirm that you have recompiled the tezos binaries `git pull && make build-deps && eval $(opam env) && make`

You can verify  if your tezos-client is working correctly by running this:

```
$ ./tezos-client rpc get /chains/main/blocks/head/context/constants
```

If that returns no errors, then TRD should work fine. If you get errors, then TRD is not the issue.

**Comment by chiptus** [comment]
Maybe TRD can run a check at startup to see if binaries are correct? Or
maybe something like "trd check-binaries"

**Comment by utdrmac** [comment]
@chiptus We shouldn't even be relying on the tezos-client directly. Everything TRD needs to do can be done using HTTP-RPC calls. I've put it on our TODO list.

**Comment by logart89** [comment]
Thank you very much i appreciate the help! it worked!

**Comment by DaylightCulture** [comment]
I was able to get it to work on my end, the compiled binaries were off. Appreciate it @utdrmac

**Comment by utdrmac** [comment]
@logart89 Can we close this then?

**Comment by jdsika** [comment]
@utdrmac should we add a "beat practice" in the documentation on how to proceed after protocol upgrades?

**Comment by utdrmac** [comment]
Yes, we can create something that basically explains "Test with -D -M 1 -V" beforehand to check.

**Comment by utdrmac** [comment]
@jdsika Can this be closed?

**Comment by jdsika** [comment]
I am closing this with #171 and #209 still open as a reminder
