### ISSUE TITLE
rules_map 

### ISSUE THREAD

**Issue by zcryptox** [tezos-reward-distributor-organization/tezos-reward-distributor#210]
one of the 'owners' wants to keep their rewards in bakery balance... setting it up in rules_map by pointing PKH: TOB doesn't work! - rewards still being delivered to KT1 ?!

**Comment by jdsika** [comment]
@dansan566 can you help here?

**Comment by zcryptox** [comment]
following up, is there a way to only calculate the ratio/rewards for owners/founders without payout? keeping rewards in the bakery balance?

**Comment by dansan566** [comment]
@zcryptox is it possible to share your config with example values?

**Comment by jdsika** [comment]
I am closing this issue - feel free to reopen and attaching your config file to discuss this further
