### ISSUE TITLE
Anonymous Statistics

### ISSUE THREAD

**Issue by jdsika** [tezos-reward-distributor-organization/tezos-reward-distributor#211]
**Describe the problem**
The option -Dp disables the sending of anonymous statistics to http://35.211.164.111:8080/trd/stats/add. Those information may be sensitive and it must be declared properly by an information at program start.

**Expected behavior**
It must be declared and the information has to made public if collected. Could you please comment on this @habanoz ?

**Screenshots**
![paste](https://user-images.githubusercontent.com/11943343/76681367-79e89c80-65f2-11ea-8805-0621606ed9e3.png)

**Environment**
 - TRD master branch

**Comment by habanoz** [comment]
@jdsika 

Collected information is properly documented. Please see notice.txt file. 

Information was used to track acceptance of TRD e.g. how many users, how large are users and trend, preferred options, failures etc.

Information was selected carefully not to include anything sensitive. Some information e.g. payment amount, stake amount was averaged out to ensure anonymity.


Listening endpoint should not be UP for a long time and no information was collected since. 

All related code sections can be removed from TRD.

**Comment by utdrmac** [comment]
Wow. I just came here to ask if we wanted to keep the stats. I noticed the IP was down and I was going to spin up a replacement on Heroku or Amazon Lamda to collect the information. Do we still want it?

**Comment by jdsika** [comment]
I am not really sure.... Can we discuss what information was collected because of what reason first?

**Comment by utdrmac** [comment]
Information collected (payment_consumer.py:187):
* Number of: founders, owners, delegators, and merged
* Total payout amount
* Number paid,  number failed, number injected, number of attempts
* cycle
* if delegate pays xfer fee (T/F)
* TRD version
* If running as background service (T/F)
* if using tzscan as data source (T/F) (would change this to tzstats)
* if using release override, the value of override
* payment offset setting
* if using docker (T/F)

Everything appears completely anonymous. No address in any way collected.

**Comment by habanoz** [comment]
https://github.com/habanoz/tezos-reward-distributor/blob/master/notice.txt

I think you already saw this file. Purpose and scope is explained. If anyone is interested to use collected data for improving product, it can be kept. Otherwise it is better to remove this feature.

**Comment by jdsika** [comment]
I think the "we can evaluate what people need" argument is quite strong. Can we make sure that everyone is allowed to review the stats, make a note on how to so it in the documentation, make a note and a link to it in the readme prominently and decide quickly what stats will be collected?
This should either be removed or online as quick as possible.

**Comment by utdrmac** [comment]
We could add a message on startup indicating what will be collected and point them to a new documentation page. It's open source so if they really care/want to see, they can just look at the code. We can add some more comments to this section of the code too.

**Comment by jdsika** [comment]
Good idea with the startup message! I dont get where the statistics are stored and who has control over that server?
Todo:
- Update documentation
- Create field in config which is true by default
- Create startup message reading from config
- Review actual statistics
- (explain to me where the hell the information is send and how to access it ;) )

**Comment by utdrmac** [comment]
Right now there is no server to accept the POST of the stats. We'd have to set one up. AWS has several "Free Tiers" we could use. A very small python script can accept the POST and insert into a DynamoDB. Would not even need to be a server, can use AWS "serverless".  That same script could accept GET which just dumps the data to html/csv/json.
