### ISSUE TITLE
Check for sufficient funds before payment

### ISSUE THREAD

**Issue by jdsika** [tezos-reward-distributor-organization/tezos-reward-distributor#220]
**Is your feature request related to a problem? Please describe.**
Most bakers use a "payment address" which is a "non ledger" address for automated payments using tezos-signer. You always have to check if enough funds are on the address used for the payment.

**Describe the solution you'd like**
I would like to check if the address has sufficient funds to do the payment. If not put the payment in a "to do queue", show a warning message and if configured send an email.

**Additional context**
It would be nice to configure a "minimum amout" on the payment address and send out a reminder email if the threshold is breached.

**Comment by jdsika** [comment]
I think this would also solve the problem of getting the wrong impression of paid rewards by receiving the rewards email notification in service mode?
If there are not enough funds it should gracefully abort and in service mode send a mail with the notice "insufficient funds" and retry the payment in X cycles

**Comment by utdrmac** [comment]
#245 Could be improved to specifically catch the "insufficient funds" error and display better logging message.

**Comment by jdsika** [comment]
@amzid is on it

**Comment by jdsika** [comment]
This is implemented with #251
