### ISSUE TITLE
Lower transaction fee to 0.001284 XTZ

### ISSUE THREAD

**Issue by denver-s** [tezos-reward-distributor-organization/tezos-reward-distributor#225]
**Is your feature request related to a problem? Please describe.**
I am paying 0.001792 XTZ while I paying 0.001284 when sending manual transactions.

**Describe the solution you'd like**
Lower the transaction fee.

**Describe alternatives you've considered**
Let user decide which fee to pay.

**Comment by SemElVik** [comment]
You can set any commission that suits you.
see `fee.ini` file
