### ISSUE TITLE
Create a docker image

### ISSUE THREAD

**Issue by chiptus** [tezos-reward-distributor-organization/tezos-reward-distributor#228]
I want to base our bakery's infra on docker, and would love to know what you think about that and what can we do? I started to work on it, my current solution is hacky, but I'll open a PR anyway so you can view my work.

**Comment by jdsika** [comment]
Blocked by issue #209

**Comment by chiptus** [comment]
I think this can be reopened, no?

**Comment by jdsika** [comment]
yes and the work can be continued in #229

**Comment by jdsika** [comment]
solved in #442
