### ISSUE TITLE
Feature Request: Ability to pay “realized rewards” instead of actual rewards.

### ISSUE THREAD

**Issue by logart89** [tezos-reward-distributor-organization/tezos-reward-distributor#231]
Hello, i want to pay my delegators in full, even if i miss endorsements or bake blocks. 

This could be done according to Krixt this way:

"basically, query RPC for baking (prio0 slots) and endorsing rights for the payout cycle * reward values = expected rewards. use that value instead of pulling the reward tx from the block"

**Comment by utdrmac** [comment]
FR noted. We will add it to our roadmap.

**Comment by NeoktaLabs** [comment]
Just like @logart89 I also would like to pay my delegators with expected rewards instead of actual rewards. I believe it could be a very useful feature for a lot of bakers out there. No major rush here tho. Thank you for the great work you're doing with TRD!

**Comment by utdrmac** [comment]
NOTES:
- We have 4 providers: rpc, prpc, tzstats, tzkt
- RPC/PRPC native API, not sure if all PRPC's provide this endpoint
  - $ curl "http://localhost:18732/chains/main/blocks/head/helpers/baking_rights?cycle=416&delegate=tz1XXXX"
  - $ curl "http://localhost:18732/chains/main/blocks/head/helpers/endorsing_rights?cycle=416&delegate=tz1XXXX"
  - Cannot filter based on priority directly, need to filter in code
- tzstats's api allows fetching of historical data quite easily:
  -   https://api.tzstats.com/tables/rights?address=tz1XXXX&cycle=200&type=endorsing&limit=5000
  -   https://api.tzstats.com/tables/rights?address=tz1XXXX&cycle=200&type=baking&priority=0&limit=5000
- tzktio has easier api:
  -   https://api.tzkt.io/v1/rights/count?type=endorsing&baker=tz1XXXX&cycle=200
  -   https://api.tzkt.io/v1/rights/count?type=baking&baker=tz1XXXX&cycle=280&priority=0
