### ISSUE TITLE
Cycle paid twice

### ISSUE THREAD

**Issue by Xa52c** [tezos-reward-distributor-organization/tezos-reward-distributor#233]
for some reason trd paid a cycle twice.

i have 2 log files showing the payments at different times.

the only explanation i can think of is that i must have run it twice during debugging.

i don't see why the second execution ran if there would be lock files, csv files in done, etc.

**Comment by jdsika** [comment]
Can you provide more information and logs here? It is a potential bug but I haven't seen it myself

**Comment by Xa52c** [comment]
i think i ran trd for cycle 237 -M 3, checked the output looked ok, CTRL-Z the execution, exited.

in another window a few minutes later i ran it again and let it complete.

reason being was that i was getting errors:

ConnectionResetError: [Errno 104] Connection reset by peer

which i think were due to running my node in public mode with too many peers (200).

[app.bak.log](https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/files/4781210/app.bak.log)
[app.log](https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/files/4781211/app.log)

**Comment by utdrmac** [comment]
Well, control-z does not halt, that backgrounds. so if you ran it in window 1, ctrl-z, then in window 2 ran it complete, then went back to window 1 and resumed, that would certainly pay twice. It sounds like you are using TRD in a way not designed which caused the issue.
You should use the `-D` option for checking that the output looks ok (that's why it exists in the first place) and not some strange terminal manipulation.

**Comment by utdrmac** [comment]
@Xa52c Is this still an open issue? Does the explanation above make sense?

**Comment by Xa52c** [comment]
The explanation makes sense but there should be some fail-safe to prevent
it from happening, imo.

**Comment by utdrmac** [comment]
There is a failsafe, `-D`. There's no way we can prevent/capture/detect oddities and misusage of the terminal. If you use the built-in methods/features for testing, you should have no issues like this.

Interestingly, there is a mechanism already in place that should have prevented 2 instances of TRD from running at the same time. Did you get any messages about a lock file?

**Comment by Xa52c** [comment]
I don't believe so but it was just a one off, I could be wrong. I use the
system service, typically.

Hope you guys are moving to a database architecture soon. The file based
architecture isn't fool proof.

**Comment by utdrmac** [comment]
Moving to SQLite is on the roadmap. It will require TONS of changes.
