### ISSUE TITLE
Payment/operation fails if single payee

### ISSUE THREAD

**Issue by GitDatEth** [tezos-reward-distributor-organization/tezos-reward-distributor#235]
**Describe the bug**

Payment is processed as batch when there is a single payment being made. This operation is injected, but fails due to some format problem.

**To Reproduce**
1. A single delegate due for payment
2. Baker address excluded for payment in by mapping TOB or using tzstats will exclud the baker from receiving a payment, leaving a single payee.

**Expected behavior**
Operation injected to node, but not included in blockchain

**Screenshots**

**Environment**
 - Source Code Build or Docker
Source code build
 - Chain mainnet, zeronet, alphanet
Mainnet
 - actual command used
python3 src/main.py -P tzstats -C 0 -M 3 -E /home/name/tezos

**Additional context**

**Comment by utdrmac** [comment]
You should not need to exclude the baker address. This is done automatically. Please share your .yaml config file.

**Comment by utdrmac** [comment]
@GitDatEth Any updates here?

**Comment by songproducer** [comment]
I also experienced a failed batch with a single payee.

**Comment by jdsika** [comment]
The config would be very helpful

**Comment by GitDatEth** [comment]
My config at the time of the issue:

version : 1.0
baking_address : tz1PFeoTuFen8jAMRHajBySNyCwLmY5RqF9M
payment_address : tz1PFeoTuFen8jAMRHajBySNyCwLmY5RqF9M
service_fee : 4.99
supporters_set : {tz1ZKtbSXJ8Er7C4qTkd3uf1w3AbunYnt9Dc}
min_delegation_amt : 100
reactivate_zeroed : True
delegator_pays_xfer_fee : True
delegator_pays_ra_fee : True
rules_map:
  mindelegation: TOB

**Comment by utdrmac** [comment]
@GitDatEth @songproducer I am not able to reproduce this issue with a single payer. Please first create a new log `mv logs/app.log logs/app.log.1` and then re-run using `-V` mode and upload your logs/app.log to this issue (don't upload the renamed log, give us the new one).

Testing on carthagenet. Baker: https://carthagenet.tzstats.com/tz1MTZEJE7YH3wzo8YYiAGd8sgiCTxNRHczR, 3 delegators.

Test 1. Ignore all delegators.
```
rules_map:
  tz1LrHNbbCLgNJZsEsTUYFvWz2THgJC8fHyX: TOB
  tz1XcnEqYkfqi6sLRpr64hFESjLUZiMLm66S: TOB
  tz1R7Crm2jWmHuq3n51CnAVutKFi4Dk8Titc: TOB
  mindelegation: TOB

root@9d9b53ac98de:/opt/trd# python3 src/main.py -f pymnt/cfg/ -E /usr/local/bin/ -P prpc -Ap https://testnet-tezos.giganode.io -A $NODE_HOST:8732 -N ALPHANET -V -M 3 -D
...
2020-08-31 20:59:19,450 - producer  - Total rewards before processing is 307,500,000 mutez.
2020-08-31 20:59:19,451 - producer  - Total rewards after  processing is 158,109,520 mutez.
2020-08-31 20:59:19,451 - producer  - Total amount to pay is 158,109,520 mutez
2020-08-31 20:59:19,452 - producer  - Total payment amount is 0. Nothing to pay!
2020-08-31 20:59:29,458 - producer  - Run mode ONETIME satisfied. Terminating ...
```

Test 2. Ignore all but 1 delegator:
```
rules_map:
  tz1XcnEqYkfqi6sLRpr64hFESjLUZiMLm66S: TOB
  tz1R7Crm2jWmHuq3n51CnAVutKFi4Dk8Titc: TOB
  mindelegation: TOB

root@9d9b53ac98de:/opt/trd# python3 src/main.py -f pymnt/cfg/ -E /usr/local/bin/ -P prpc -Ap https://testnet-tezos.giganode.io -A $NODE_HOST:8732 -N ALPHANET -V -M 3 -C 331
....
2020-08-31 21:07:40,742 - consumer0 - <-- Verbose : Answer is |[ { "contents":
      [ { "kind": "transaction",
          "source": "tz1MTZEJE7YH3wzo8YYiAGd8sgiCTxNRHczR", "fee": "1792",
          "counter": "823622", "gas_limit": "15385", "storage_limit": "257",
          "amount": "89534610",
          "destination": "tz1LrHNbbCLgNJZsEsTUYFvWz2THgJC8fHyX",
          "metadata":
            { "balance_updates":
                [ { "kind": "contract",
                    "contract": "tz1MTZEJE7YH3wzo8YYiAGd8sgiCTxNRHczR",
                    "change": "-1792" },
                  { "kind": "freezer", "category": "fees",
                    "delegate": "tz1Ke2h7sDdakHJQh8WX4Z372du1KChsksyU",
                    "cycle": 335, "change": "1792" } ],
              "operation_result":
                { "status": "applied",
                  "balance_updates":
                    [ { "kind": "contract",
                        "contract": "tz1MTZEJE7YH3wzo8YYiAGd8sgiCTxNRHczR",
                        "change": "-89534610" },
                      { "kind": "contract",
                        "contract": "tz1LrHNbbCLgNJZsEsTUYFvWz2THgJC8fHyX",
                        "change": "89534610" } ], "consumed_gas": "10207" } } } ],
    "signature":
      "edsigtzp6jsjfKr5k3Ep1FCbRPmahvR2coJjwzC3gHsKkucb6RHMmWwMk6x1HrLz9MkefthSKb2geCqGY1cKKHLYkGCcp8aoPZ9" } ]|
2020-08-31 21:07:40,743 - consumer0 - Injecting 1 operations
2020-08-31 21:07:40,743 - consumer0 - --> Verbose : Command is |/usr/local/bin/tezos-client -A 172.17.0.5 -P 8732 rpc post /injection/operation with '"1911c9a3360e820b986cf4c5c1c8b018cfb733786c0aab9f19d29c835c647e216c0013f52adebe8c41bcdf8167ecbcb8efd17fdb3351800ec6a2329978810292e1d82a00000d495f43307b913913ae4c894c3c06e70f56a1ba00ce6bea2eb4e55f7bd2e1697fc161344372ffd6ebea88d3b88bce53ae0c5f145948b4deba37963d560f8d4c80c1719effa363df5f8954ae929d08fd38b54a5a08"'|
2020-08-31 21:07:40,816 - consumer0 - <-- Verbose : Answer is |"opKWrAFcqGQCmr9HBVfJRXyM68UP92RDReCJN2opPmgj7MfRsvG"|
2020-08-31 21:07:40,816 - consumer0 - Operation hash is opKWrAFcqGQCmr9HBVfJRXyM68UP92RDReCJN2opPmgj7MfRsvG
```

There appears to be no issue in paying a single delegator.

**Comment by GitDatEth** [comment]
Interesting. Curious if it's only happening with a non-batch payment using a Ledger. My local node would receive the operation, but it would never be picked up and processed by a baker. It would only process as a batch operation (by including my baker address as the second payee).

**Comment by utdrmac** [comment]
If you could provide the verbose log, that would be extremely helpful. The normal log, not so much. You'd have to recreate a failure with `-V`

**Comment by jdsika** [comment]
#430 is the duplicate
