### ISSUE TITLE
Merge retry_failed.py into main.py

### ISSUE THREAD

**Issue by amzid** [tezos-reward-distributor-organization/tezos-reward-distributor#261]
We often needed to adapt changes made in main.py to retry_failed.py (see #256 e.g.) after some code changes in other parts.
Many people are also not aware of this file or are not sure about how or when to use it.
I suggest to fuse both files into one single file main.py.

**Comment by amzid** [comment]
The use of run modes 1 (forever) and 2 (pending) ensures trying to pay all failed payments before proceeding with the new payments. This feature is blocked for run mode 3 (one single cycle).
The current logic of the TRD makes use of retry_failed.py in order to retry the failed payments for one single cycle.
The current behavior of the TRD is the following: If the user uses main.py to retry failed payments for one single cycle using the run mode 3, then the program would stop because of the presence of a failed payment report for that cycle.
I suggest to remove retry_failed.py and make sure to retry the payment for that single cycle if the user chooses to do so (instead of blocking the retry_failed_payment function if run mode is 3, we call the function but make sure that it retries only the payments for the requested cycle).

**Comment by jdsika** [comment]
@amzid I think this can be closed.
