### ISSUE TITLE
Check if TzStats API can be used more efficient

### ISSUE THREAD

**Issue by dansan566** [tezos-reward-distributor-organization/tezos-reward-distributor#262]
**Is your feature request related to a problem? Please describe.**
I talked to Alex from TzStats. He would like to talk to us on how we use the TzStats API within TRD. There might be a way to speed up the API query enormously. I've also talked to him about this (https://medium.com/@_MisterWalker_/we-all-were-wrong-baking-bad-and-most-bakers-were-using-wrong-data-to-calculate-staking-rewards-a8c26f5ec62b). He said he fixed it as well. If I use TzStats within the TRD, can I be sure that my payout is correct? 

You can contact Alex via his discord channel: https://discord.com/invite/D5e98Hw

**Comment by gaia** [comment]
I thought you used `-P tzkt` ? per #263 ?

**Comment by dansan566** [comment]
> I thought you used `-P tzkt`, per #263 ?

Yes, I did use `-P tzkt`, but I also like the variation within TRD. If we can speed up tzstats as well, then this would be another great achievement.
