### ISSUE TITLE
Current Version, Fresh Install: Unknown format code 'f' for object of type 'str'

### ISSUE THREAD

**Issue by gaia** [tezos-reward-distributor-organization/tezos-reward-distributor#263]
**Describe the bug**
`Message: 'Fetching delegator {} current balance failed, will retry: {}'
Arguments: ('tz1iJDv8e3D9G641j696nYTV854He41qu2bV', ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='mainnet-tezos.giganode.io', port=443): Read timed out. (read timeout=5)",),))` this is prob OK, just a timeout error

`producer  - Error at payment producer loop: 'Unknown format code 'f' for object of type 'str'', will try again.` this is not ok.

**To Reproduce**
`python3 src/main.py -M 3 -P prpc -Dp -D -C 264`

**Expected behavior**
as in previous cycles (older version of TRD), for payment to be calculated

**Screenshots**
upon request

**Environment**
 - git pull
 - pretty std config, has been in use for over 1 year with no changes
 - mainnet
 - see "To Reproduce"
 - ubuntu 18.04

**Comment by dansan566** [comment]
I've got a similar error: 
Traceback (most recent call last):
```
  File "/Users/dl/tezos-reward-distributor/src/pay/payment_producer.py", line 254, in try_to_pay
    self.create_calculations_report(reward_logs, report_file_path, total_amount)
  File "/Users/dl/tezos-reward-distributor/src/pay/payment_producer.py", line 331, in create_calculations_report
    pymnt_log.skipped, pymnt_log.skippedatphase, pymnt_log.desc, pymnt_log.paymentaddress))
ValueError: Unknown format code 'f' for object of type 'str'
```

**Comment by dansan566** [comment]
I have made a dry run with `python3 src/main.py -C 265 -D -P tzkt -M 3 -O 10 -V` before. It started a loop and the signer signed at least 20 transactions until I've canceled the process.

**Comment by gaia** [comment]
Traceback

```
Traceback (most recent call last):
  File "/home/tezos/scripts/tezos-reward-distributor/src/pay/payment_producer.py", line 254, in try_to_pay
    self.create_calculations_report(reward_logs, report_file_path, total_amount)
  File "/home/tezos/scripts/tezos-reward-distributor/src/pay/payment_producer.py", line 331, in create_calculations_report
    pymnt_log.skipped, pymnt_log.skippedatphase, pymnt_log.desc, pymnt_log.paymentaddress))
```

**Comment by amzid** [comment]
Can you pull the master branch again and check if you still get the problem?

**Comment by dansan566** [comment]
I just made a dry run with `python3 src/main.py -C 264 -D -P tzkt -M 3 -O 10  -V`. I did not encounter the error!

**Comment by gaia** [comment]
I was able to process payments for 2 cycles, no problem!
