### ISSUE TITLE
Tezos v8.0 will have "multiple transfers" command

### ISSUE THREAD

**Issue by denver-s** [tezos-reward-distributor-organization/tezos-reward-distributor#271]
Hi, just wanted you to know that a MR has been merged regarding multiple transfers command.
I don't know if this will be better than the current batch procedure.

`tezos-client multiple transfers from <src> using <transfers.json>`

Source: https://gitlab.com/tezos/tezos/-/merge_requests/1849

**Comment by denver-s** [comment]
Tezos v8.0-rc1 has been released, which contains "multiple transfers".

* Added client command `multiple transfers from <src> using <transfers.json>`
to perform multiple operations from the same address in a single command.

https://gitlab.com/tezos/tezos/-/blob/v8-release/CHANGES.md

**Comment by utdrmac** [comment]
@denver-s TRD does not use the tezos-client to create transactions. All the txns are batched internally and are injected directly to the node. This new feature of the tezos-client simply allows someone to create the same batches TRD has been using, since the beginning, on the CLI.
