### ISSUE TITLE
Unable to send rewards to a delegator contract

### ISSUE THREAD

**Issue by pawan-tezsure** [tezos-reward-distributor-organization/tezos-reward-distributor#274]
**Describe the bug**
Unable to send rewards to a delegator contract
**To Reproduce**
1. Use smartpy to deploy a contract (which should have more than 2 entry points) which can delegate its tokens to a baker.
2. Try to send rewards to the delegator contract.

**Expected behavior**

For sending tokens from an EOA account to a contract address, normal transfer would not work. We need to invoke an entry point to transfer token to contract, for invoking a contract we should have its Michelson parameters, sending 'Unit' will not just do the job because the Michelson parameters depend upon number of entry point and the name of entry points.

**Comment by jdsika** [comment]
#270 duplicate. @amzid can you have a look here?

**Comment by jdsika** [comment]
closing as discussion is in the other issue
