### ISSUE TITLE
a very long wait for inclusion batch in the block.

### ISSUE THREAD

**Issue by SemElVik** [tezos-reward-distributor-organization/tezos-reward-distributor#275]
*4 batch is not included in the blockchain. batch is lost*
↓
after the last TRD update I have very long delays in batch.
The first 3 batch seem to pass as usual, but the 4 batch hangs for a very long time before the package is included into the block.
I waited 1.5 hours. and the package was never included in the blockchain.   (13 transactions are lost).
         i stopped TRD, (CTR+C)            
   -  the report is not generated in the `failed` folder.   and it is not created in the folder `done`

the first time the batch went through a long time after the TRD stopped.
this time, it seems to me, batch is lost. and I need to do the calculation & pay manually

it should not be. what is the problem.  it's no class....

**Comment by dansan566** [comment]
I can't confirm the issue. I just sent out 4 batch payments with command `python3 src/main.py -C 275 -P tzkt -M 3 -O 10` using the newest TRD version.

**Comment by SemElVik** [comment]
`python3 src/main.py -C 275 -M 3`

**Comment by SemElVik** [comment]
the same problem.
batch 4 does not get confirmed on the blockchain

**Comment by amzid** [comment]
Can you rerun with the -V flag and send us the log file?

**Comment by SemElVik** [comment]
```python3 src/main.py -C 278 -P tzkt -M 3 -O 10```

in cycle 277 - the delay between batch 3 and batch 4 payments was 17 minutes.
in cycle 288 - the delay between batch 3 and batch 4 payments was 24 minutes. 
when usually waiting 2 blocks between batch.

if necessary i will do a Dry run with the -V flag...

**Comment by SemElVik** [comment]
the last cycles run as needed, there are no special delays or failures.
i use tzkt *`python3 src/main.py -C 275 -P tzkt -M 3 -O 10`* instead of the default *`python3 src/main.py -C 275 -M 3`*

**Comment by SemElVik** [comment]
between batch 3 and batch 4, the waiting time for confirmation was 2+ hours.
the problem remains. i stopped TRD (Ctrl/C).
in some cases I can't wait for the hash to be confirmed and I have to make a manual batch payment.

the command does not matter:
`python3 src/main.py -C 281 -P tzkt -M 3 -O 10` or `python3 src/main.py -C 281 -M 3`

in this case, can I re-relay the failed hash with a singly command?

**Comment by SemElVik** [comment]
what does the label mean? *`blocked`*

**Comment by jdsika** [comment]
We don't have enough information to debug it... Maybe you could provide the specifics to amzid in the baker slack to keep it private?

**Comment by SemElVik** [comment]
ok.
everything is going well at the moment.
if the error persists, I will write to him in slack personally.
thanks.

**Comment by jdsika** [comment]
Issue will be closed. Please reopen if the error persists on Delphi network testing at least with v7.5 tezos client.
