### ISSUE TITLE
[RPC/TzKt] TRD support for Dexter liquidity pool payouts (continued)

### ISSUE THREAD

**Issue by dansan566** [tezos-reward-distributor-organization/tezos-reward-distributor#276]
**Is your feature request related to a problem? Please describe.**
camlCase officially released [Dexter](https://dexter.exchange/) a couple of days ago. They currently state the following on their website "In order to ensure that liquidity providers receive their rewards even if they remove their liquidity from a Dexter contract, we delegate only to bakers that use the tzpay tool." The TRD should also be able to handle Dexter XTZ liquidity pool payouts. More options are always better! 

**Describe the solution you'd like**
I've talked to @DefinitelyNotAGoat, who is the creator of tzpay and member of the camlCase team. He supports this effort. It’s worth noting to add this functionality the TRD will have to be able to read the contract storage as well as query a Big Map, he said. He also offered his help! 

Most of the logic to make tzpay work with Dexter contracts is here: 
https://github.com/goat-systems/tzpay/blob/dexter/internal/payout/dexter.go

**Comment by jdsika** [comment]
The issue for tzkt has been opened [here](https://github.com/baking-bad/tzkt/issues/21)

**Comment by amzid** [comment]
A review from @dansan566 points out that the specials_map does not work with dexter-based payouts. This should be fixed.

**Comment by dansan566** [comment]
@jdsika Can be closed! Dexter is no longer a thing.
