### ISSUE TITLE
configure : AttributeError: 'Namespace' object has no attribute 'api_base_url'

### ISSUE THREAD

**Issue by xiduis15** [tezos-reward-distributor-organization/tezos-reward-distributor#279]
**Describe the bug**
configure.py doesn't run
AttributeError: 'Namespace' object has no attribute 'api_base_url'

**To Reproduce**
have a failed batch.
run configure.py

**Expected behavior**
work

**Screenshots**
`user@mynode:~/tezos-reward-distributor$ python3 src/configure.py -V --executable_dirs /home/user/.opam/for_tezos/bin/ -A https://mainnet-tezos.giganode.io:443 -P rpc`

2020-10-12 07:46:33,850 - MainThread - Tezos Reward Distributor Baker Configuration Tool is Starting
2020-10-12 07:46:33,850 - MainThread - Arguments Configuration = {
 "reward_data_provider": "rpc",
 "network": "MAINNET",
 "reports_base": "\~/pymnt/reports",
 "config_dir": "\~/pymnt/cfg",
 "node_addr": "https://mainnet-tezos.giganode.io:443",
 "executable_dirs": "/home/user/.opam/for_tezos/bin/",
 "docker": false,
 "verbose": true,
 "dry_run": false
}
This application will help you configure TRD payouts for your bakery. Type enter to continue >
Specify your baking address public key hash (Processing may take a few seconds) >
tz1xxxxxxxxxxxxxxxxxxxx
Traceback (most recent call last):
File "src/configure.py", line 518, in <module>
    main(args)
File "src/configure.py", line 413, in main
    callbacks\[fsm.current\](command)
File "src/configure.py", line 82, in onbakingaddress
    api_base_url=args.api_base_url)
AttributeError: 'Namespace' object has no attribute 'api_base_url'

**Environment**
Ubuntu 18.04.5 LTS fresh install
    Opam tezos install
    Chain mainnet
RPC node : mainnet-tezos.giganode
    actual command used
    user@mynode:~/tezos-reward-distributor$ python3 src/configure.py -V --executable_dirs /home/user/.opam/for_tezos/bin/ -A https://mainnet-tezos.giganode.io:443 -P rpc
    Additional context
    have the latest code

**Comment by utdrmac** [comment]
@xiduis15 Are you comfortable testing a fix? If so, open configure.py in your text editor, go down to the bottom, line 512. Should be a blank line. Add this `add_argument_api_base_url(parser)` so it looks like the lines above it. Save. Exit. Re-run configure.py as you did and let me know if that fixes it.

**Comment by Michshelle** [comment]
Hey utdrmac,

I happened to fin this open issue and I tried the above solution you mentioned on os catalina;
`Traceback (most recent call last):
  File "src/configure.py", line 512, in <module>
    add_argument_api_base_url(parser)
NameError: name 'add_argument_api_base_url' is not defined`

In my case, it still cannot work.  Thanks.

**Comment by utdrmac** [comment]
@Michshelle You have the latest code pull? Make sure to `git pull` before trying the fix.

**Comment by Michshelle** [comment]
> @Michshelle You have the latest code pull? Make sure to `git pull` before trying the fix.

I think I've made it work by adding add_argument_api_base_url in line 21 as mentioned in my previous comment above.

**Comment by utdrmac** [comment]
Oh, I see what you meant. Ahh, yes, the import, forgot about that aspect. Let's see if those fixes work for @xiduis15 and I'll make a PR for it.

**Comment by xiduis15** [comment]
it's ok for me.
