### ISSUE TITLE
.csv file shows incorrect calculations

### ISSUE THREAD

**Issue by SemElVik** [tezos-reward-distributor-organization/tezos-reward-distributor#283]
this `git` is pulled out today. `5f64db8e47270648117171210ca04e0d7ab0df18`

calculation for a future cycle (for example, cycle 284-288) shows inaccurate data.
please check the  precision of the calculation.

**Comment by amzid** [comment]
What provider are you using? tzstats?
What are you comparing the results to?

**Comment by SemElVik** [comment]
I've always done calculations like this:  `python3 src/main.py -C 284 -D -P tzstats -M 3 -R -5`
I compare it with my calculations already made.

**Comment by amzid** [comment]
Is the difference in the total amount of rewards, or in the staking balances of the delegators?

**Comment by SemElVik** [comment]
total amount and staking balance of delegators.
i will send the files to you in slack

**Comment by amzid** [comment]
Can you check if #287 solves your issue, please?
If you have further problems, you can send me on slack.

**Comment by SemElVik** [comment]
yes. it works.

**Comment by jdsika** [comment]
@amzid please use the Keywords correctly to autoclose issues
