### ISSUE TITLE
Delphi: lower the default fee

### ISSUE THREAD

**Issue by denver-s** [tezos-reward-distributor-organization/tezos-reward-distributor#303]
**Is your feature request related to a problem? Please describe.**
With the introduction of protocol 007, the minimum fee to be payed has decreased.

**Describe the solution you'd like**
Calculate and set a lower default fee (now 1792), gas_limit (now 15385) and storage_limit (257).

https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/blob/ed94f3866de0801a0e90ead9a62564121e1435df/fee.ini#L2

**Comment by jdsika** [comment]
I already set the storage:limit to 257 / 4 = 65 in the linked PR. Can you experiment on what the new other values are? I took the information from [here](https://blog.nomadic-labs.com/delphi-changelog.html)

**Comment by denver-s** [comment]
I am testing in --dry-run mode some transactions (not batch).

`./tezos-client transfer 0 from myaddress to KT1address --storage-limit 65 --gas-limit 3230 --fee 0.000574 --dry-run`

And it works.

**Comment by jdsika** [comment]
@dansan566 can we test with real transactions? I don't trust dry run. Please use v7.5 as the gas calculation is broken in v7.4

**Comment by denver-s** [comment]
I want to add that if there are no KT1 addresses, we could lower the limits even more:

./tezos-client transfer 0 from myaddress to tz1address --storage-limit 65 --gas-limit 1427 --fee 0.000576 --dry-run
