### ISSUE TITLE
TRD keeps exiting with an unknown protocol error.

### ISSUE THREAD

**Issue by dawsy8888** [tezos-reward-distributor-organization/tezos-reward-distributor#305]
Hi

Hoping someone can help.

TRD keeps exiting with an unknown protocol error.

I have deleted all the pymnt and tezos-reward-distributor directories and reinstalled, tried my old .yaml file and even the example one and the error keeps coming up.

Additionally, I am running TRD as a service and after the recent upgrade my node crashed and the context became corrupted. I had to import a backup to get going again. It seems that the tezos-reward service kept exiting and restarting and drained the memory. 

The error occurs as a service or when running from the cli prompt.

Any ideas ?

Thanks 
Steve

![Screen Shot 2020-11-14 at 12 26 19 pm](https://user-images.githubusercontent.com/28333611/99135073-af0f2800-2674-11eb-8e07-f18a5d01bcd7.png)

**Comment by jdsika** [comment]
I think your node and Tezos binaries are corrupt. I would try recompiling the binaries v7.5 and cleaning the Tezos directories before.

**Comment by lexxor79** [comment]
Hello,

I have the same issue...
Update Kiln, node up-to-date but TRD error message : "unknown protocol version"

**Comment by dawsy8888** [comment]
It was pointing at an old version of the tezos client

**Comment by dawsy8888** [comment]
TRD was pointing at old version of client. Pointed it at the folder with the version and all is good
