### ISSUE TITLE
Wrong version?

### ISSUE THREAD

**Issue by nurikabe** [tezos-reward-distributor-organization/tezos-reward-distributor#312]
**Describe the bug**

Just ran the v7.0 tag but see TRD reporting the following version:

020-11-15 17:57:13,622 - MainThread - TRD version 5.13 is running in interactive mode.

**To Reproduce**
1. Checkout v7.0 tag as branch
2. Run in dry-run mode, for example `$ python3 ./src/main.py -D -V -C285 -M3 -E ~/delphi/tezos -A localhost:18732`

**Expected behavior**
Version output should match tag, eg:

TRD version 7.0 is running in interactive mode.

**Screenshots**

**Environment**
 - Source Code
 - Debian
 - mainnet

**Comment by jdsika** [comment]
good catch - we fixed it for the release we are doing right now :)

**Comment by nurikabe** [comment]
@jdsika Same problem again with the latest Edo version.
