### ISSUE TITLE
Increase MAX_TX_PER_BLOCK

### ISSUE THREAD

**Issue by denver-s** [tezos-reward-distributor-organization/tezos-reward-distributor#323]
**Is your feature request related to a problem? Please describe.**
Delphi protocol increases the number of transactions allowed in a block. Citing from [Nomadic Labs' blog article](https://blog.nomadic-labs.com/delphi-official-release.html):

- A block may now include 3.5 times more simple tz to tz ops

**Describe the solution you'd like**
Change the value of MAX_TX_PER_BLOCK, which is currenty set to 200:
https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/blob/9b3ca82ad80871905bc51d013526fe2f6ebef748/src/pay/batch_payer.py#L15

**Comment by jdsika** [comment]
Good catch, let's increase in a conservative way.

**Comment by utdrmac** [comment]
Should we make it a configurable setting?

**Comment by jdsika** [comment]
I would go for a calculation depending on the current gas limits with a safety factor of e.g. 15% which is also part of the fee.ini ?

**Comment by utdrmac** [comment]
Notes:
"minimal_fees": "0.0001", "minimal_nanotez_per_gas_unit": "100", "minimal_nanotez_per_byte": "250"

fee = minimal_fees + 
      (minimal_nanotez_per_gas_unit * consumed_gas) +
      (minimal_nanotez_per_byte * tx_size_in_bytes)
fee = fee * 1.05 // 5% padding

**Comment by utdrmac** [comment]
I'm having a very difficult time figuring out how to turn each transaction into a way of calculating "byte size". I'm not sure how much benefit it will have anyways.

**Comment by amzid** [comment]
Why do we need to calculate byte size?

**Comment by jdsika** [comment]
I will push this to v8.5 as there is no final solution.

**Comment by utdrmac** [comment]
> Why do we need to calculate byte size?

@amzid , Carlo said above he would like TRD to calculate based on "current gas limits". Doesn't that require knowing the byte size of the txn? or am I completely missing something?

**Comment by utdrmac** [comment]
I think this can be closed. I was unable to increase above 230 txn per batch without getting limited by the 16K operation size.

**Comment by denver-s** [comment]
Really? Were there a lot of KT1 delegators?
I tested and had success with almost 300, mostly tz1 wallets.

**Comment by utdrmac** [comment]
Not a lot of KT1s, 37/570. The rest all tz1. I was able to get it set at 250. Anything above caused error.

**Comment by jdsika** [comment]
So we have actually found a practical value that with good confidence works in all cases. @utdrmac the only thing I see is to put the value in the config and give it a 200 as default value?

**Comment by utdrmac** [comment]
https://gitlab.com/tezos/tezos/commit/3ff6bc8da9f8941b65fb9be4e51d3de1e93bfaed

Max operation length will be doubled to 32K in Florence
