### ISSUE TITLE
Verbose logging breaking change

### ISSUE THREAD

**Issue by utdrmac** [tezos-reward-distributor-organization/tezos-reward-distributor#326]
**Describe the bug**
`-V` is no longer a simple flag. 

```
 main.py: error: argument -V/--verbose: expected one argument
```

You are required to specify `-V on` if you want verbose logging. This is a backwards-breaking change were before you could simply do `-V` to enable verbose logging.

**To Reproduce**
1. Download latest master
2. Attempt to run using `-V`
3. See error

**Expected behavior**
`-V` should continue to behave as before

**Comment by habanoz** [comment]
@utdrmac 

As per our earlier discussion, this change was a necessity. If you have a suggestion, please let us know. I will gladly apply.

Until a suggestion is made, I close this issue.
