### ISSUE TITLE
Separating plugins (telegram, twitter) messages

### ISSUE THREAD

**Issue by BakeTz** [tezos-reward-distributor-organization/tezos-reward-distributor#327]
I set up the Telegram plugin and start receiving all messages in one place like: "Low Payment Address Funds Warning" and "Reward Payouts for Cycle 294 Completed Successfully!". Can we separate official and operational messages, because I don't want to my delegators see unnecessary massages like "Low Payment Address Funds Warning"?

The solution can be:
- configure official and operational messages by chat_ids
- configure turn on/off messages by chat_id

**Comment by jdsika** [comment]
Yes, the bot is more for internal purposes yet - ergo your own telegram channel with the maintainers of the baker present. I think it is a good idea that I scheduled for the v8.5 after confirmation of the other maintainers.

**Comment by utdrmac** [comment]
FYI, I'm working on this.
