### ISSUE TITLE
Re-run for a given cycle

### ISSUE THREAD

**Issue by nurikabe** [tezos-reward-distributor-organization/tezos-reward-distributor#328]
**Is your feature request related to a problem? Please describe.**

Something went wrong with my last run and only eleven payments were generated.  Still not sure why.

**Describe the solution you'd like**

I have a `calculations/295.csv` and `payments/done/295.csv` files with the eleven completed calculations/payments.

I'd like to be able to re-run cycle 295 where the eleven completed payments are ignored.

As far as I can see TRD only safely ignores completed cycles rather than payments within a cycle.

**Describe alternatives you've considered**

Fancy regex magic

**Comment by utdrmac** [comment]
@nurikabe Please check out #321 and verify same issue. Several were affected by this.
What I did: i took those 11 inside the 'done/295.csv' and added them to the yaml config rules_map as 'TOB', deleted the 295.csv and re-ran 295 (after updating the code of course).

**Comment by nurikabe** [comment]
Yep, that was it.  Took me a second to undersand "TOB", but did as you suggested once I figured it out.  Thanks.

**Comment by nurikabe** [comment]
I still think this would be a good feature...

**Comment by jdsika** [comment]
-M 4 should be the mode you desire?

**Comment by nurikabe** [comment]
@jdsika Probably not. I'd like it to ignore successful payments in a given cycle and process all remaning.
