### ISSUE TITLE
Plugins payment tx URL

### ISSUE THREAD

**Issue by Primate411** [tezos-reward-distributor-organization/tezos-reward-distributor#329]
**Is your feature request related to a problem? Please describe.**
Low information stakers can’t tell how much they’re getting paid with each cycle. 

**Describe the solution you'd like**
I would like the plug-in payment notices to include a link to the payment batch payment on any is the blockchain explorers. 

**Describe alternatives you've considered**
I post the link manually. 

**Additional context**
Some more variables in general would really elevate the plug-in notifications!

**Comment by utdrmac** [comment]
Do these low information stakers not use the Telegram Notifier Bot? That would tell them all the info they need.

Please provide examples of variables you'd like to use in your message templates.

**Comment by Primate411** [comment]
Some use it, most don’t know about it. The main improvement I’m seeking is a link to the payment tx so stakers can click right on the telegram/Twitter plugin generated message and verify their payment. 

When I wrote variables I mainly meant the ability to customize the whole payment message that’s delivered thru the plugins. Like if there is a line in the configs with the message that we can send for each delivery method.

**Comment by utdrmac** [comment]
@Primate411 What I don't understand is that the message would contain a link to the batch payment tx. So, 1 op containing 500+ txns. Is that beneficial to your uninformed stakers? Would they know how to search the batch to find their transaction?

Can you provide an example of "I post the link manually"?

**Comment by Primate411** [comment]
![25EEA090-3E0E-4A9F-928F-09F999831B90](https://user-images.githubusercontent.com/36507842/100520288-07f9b880-316b-11eb-962c-730513a69ad9.png)

Here’s an example. Top is the way my stakers prefer, bottom is how it’s currently done. 

I realize not everyone might want this functionality, hence the variable comment to be able to include this optional link along with other things like hashtags or links to our help desk email as so on. This will make trd an even richer user experience product.

**Comment by utdrmac** [comment]
@Primate411 I've been thinking about this all day. I don't want to get into "feature creep" where many little features are implemented for very small number of use-cases. I feel like you could solve your issue by utilizing the webhooks plugin. This plugin sends all the transaction data (including opHash). Your website can absorb this info and turn it into A) blog post, B) "check your balance" feature, etc. Then in your telegram, just have a generic message that says 'Payouts Completed. Visit website.com/rewards to see how much you earned!' What do you think of this?

As a side note, I am working on custom title/message content, and having 'admin' messages, and 'public' messages.

**Comment by Primate411** [comment]
I appreciate your consideration and the solution you proposed is definitely sufficient for my needs.
