### ISSUE TITLE
tzkt and tzstats providers do not support delphinet

### ISSUE THREAD

**Issue by utdrmac** [tezos-reward-distributor-organization/tezos-reward-distributor#331]
https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/blob/cb022b3a9e4a1d82314bf5f9361396c13e1b5952/src/tzkt/tzkt_api.py#L35

No support for delphinet

**Comment by amzid** [comment]
Maybe we should consider changing all the stuff depending on the name of the current testnet to a single file to make editing easier, maybe Constants.py? Even better if we can change all or at least reduce as many as possible instances of e.g. delphinet to a single one named testnet which can be configurable according to the -N flag?
