### ISSUE TITLE
logger.info produces double output

### ISSUE THREAD

**Issue by utdrmac** [tezos-reward-distributor-organization/tezos-reward-distributor#332]
@habanoz Using cb022b3a9e4

logger.debug() does not seem to be affected by this, only logger.info().
Additionally, this issue only happens after init() is called. If you add a simply logger.info("HELLO") before init() in main.py, this issue is not seen. Add the same line after init() and you'll see duplicate.

```
$ python3 src/main.py -f pymnt/cfg/ -r pymnt/reports/ -E /opt/tezos_mainnet/tezos -A 127.0.0.1:8732 -P rpc -M 3 -O 300 -C 296 -V on -D
...
...
2020-11-30 04:40:06,225 - MainThread - --------------------------------------------
--------------------------------------------
2020-11-30 04:40:06,226 - MainThread - BAKING ADDRESS is tz1asdfasffa
BAKING ADDRESS is tz1asdfasffa
2020-11-30 04:40:06,226 - MainThread - PAYMENT ADDRESS is backup
PAYMENT ADDRESS is backup
2020-11-30 04:40:06,226 - MainThread - --------------------------------------------
--------------------------------------------
2020-11-30 04:40:06,227 - MainThread - [Plugins] Loaded plugin Telegram
[Plugins] Loaded plugin Telegram
```

**Comment by habanoz** [comment]
@utdrmac 

Thanks for the fine details.  I check out your branch, but unable to reproduce. It does not occur in master either. 

I will leave this issue open. I Will check again after your job is finished.

**Comment by habanoz** [comment]
@utdrmac 

I made more tests. However, still unable to reproduce. Would you mind doing the same test in branch issue_332?
