### ISSUE TITLE
Why is plugin tag is required in baking config ?

### ISSUE THREAD

**Issue by habanoz** [tezos-reward-distributor-organization/tezos-reward-distributor#334]
**Describe the bug**
Baking config is not accepted if plugins and enabled tags are not present?

**Expected behavior**
The absence of plugins should be allowed. In this case, no plugin is initialized.

**Comment by utdrmac** [comment]
The purpose behind requiring this was to force people to pay attention to upgrade procedures. I don't consider it a bug.

**Comment by habanoz** [comment]
> I don't consider it a bug.
Neither do I! It is not a feature either. 

> The purpose behind requiring this was to force people to pay attention to upgrade procedures.
I do not know what procedures needed. I still believe it is somewhat annoying to force users to add a configuration that is not used. I urge you to reconsider this necessity. 

If you believe there is no way around, you may close this issue.
