### ISSUE TITLE
Add flag to ignore error "Payment failed report for cycle X is present. No payment will be run for the cycle."

### ISSUE THREAD

**Issue by denver-s** [tezos-reward-distributor-organization/tezos-reward-distributor#337]
**Is your feature request related to a problem? Please describe.**
When a payment fails, a CSV file is created under `/pymnt/reports/<tz1xxxx>/payments/failed/<cycle>.csv` which prevents the retry in case the user fixed the previous error. The user now has to manually remove that CSV file and try again.

**Describe the solution you'd like**
Add a `--force` flag which bypasses or removes the CSV of the previous failed payment report.

**Comment by utdrmac** [comment]
@denver-s Have you looked at the retry mode? `-M 4` The purpose of this mode is to retry failed payments.

**Comment by jdsika** [comment]
I will close this issue and ask @denver-s to use the --help functionality and give feedback if the -M 4 mode is not explained well enough and how to improve it.

**Comment by denver-s** [comment]
Sorry to reply so late. I think the documentation needs an improvement.
For example, there is no "-M 4" [explained here](https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/blob/master/docs/run.rst) (and it's not easy to understand other modes).
