### ISSUE TITLE
Plugin - Report File Support

### ISSUE THREAD

**Issue by habanoz** [tezos-reward-distributor-organization/tezos-reward-distributor#344]
**Is your feature request related to a problem? Please describe.**
If users have the report file with payout notification, e.g. mail would be very nice. This will make report files more accessible. This way report files are stored in other servers which can be seen as a backup method.  

**Describe the solution you'd like**
All plugins should have an option to include payment and calculation reports in the notification if the underlying platform supports it.

**Comment by utdrmac** [comment]
@habanoz Webhook and Email plugins already support this. Twitter and Telegram don't. I'm confused.

**Comment by habanoz** [comment]
> Webhook and Email plugins already support this

Great.

> Twitter and Telegram don't.

Adding to Twitter would be very useful. Especially the calculation report. Delegators usually follow The baker’s account on Twitter. Accessing to the reports would make them happier.

**Comment by utdrmac** [comment]
You can attach files to tweets? The twitter API says you can only attach videos and images to tweets. Can you clarify more what you are looking for?

**Comment by habanoz** [comment]
> The twitter API says you can only attach videos and images to tweets. 

OK. Thanks.

Closing.
