### ISSUE TITLE
Email plugin not detected as enabled

### ISSUE THREAD

**Issue by rzup** [tezos-reward-distributor-organization/tezos-reward-distributor#345]
Hi! First of all, thanks your work, love the new changes!

I'm having some problems with the new plugin config. I'm using e-mail for payment notifications. I've moved the settings to the config file and the config file reads them fine, but when I start the distributor - it says no plugins enabled. 

Current config in the tz-account.yaml:

....
delegator_pays_ra_fee : True
plugins:
  enabled:
  email:
    smtp_user: email@gmail.com
    smtp_pass: password
    smtp_host: smtp.gmail.com
    smtp_port: 587
    smtp_tls: true
    smtp_sender: email@gmail.com
    smtp_recipients:
      - receiever@mail.com

The log when the distributor starts:
MainThread - [Plugins] No plugins enabled

Everything else works fine, the payouts work, no error present in the logs. Was wondering what could be the problem for not detecting enabled e-mail notifications?

**Comment by jdsika** [comment]
You need to put email under enabled:

... But as you are not the first I will leave it as a bug to improve customer experience

**Comment by rzup** [comment]
Hi @jdsika 

I have put the email under enabled as you can see it in the c/p from the config yaml file in the above post.

Current setup:
plugins:
   enabled:
   email:
        smtp_user: email@gmail.com
        smtp_pass: password
        smtp_host: smtp.gmail.com
        smtp_port: 587
        smtp_tls: true
        smtp_sender: email@gmail.com
        smtp_recipients:
             - receiever@mail.com

Its the same as in the example config. But when I start the distributor, no plugins are enabled. What could be the problem with my current config in the yaml file?

**Comment by jdsika** [comment]
@utdrmac the configuration is not well understood. I think we have to modify it. The example should state the difference in example between "disabled" and "enabled"

**Comment by utdrmac** [comment]
@rzup Please look at the documentation:
https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/blob/master/docs/plugins.md

It clearly shows how to enable a plugin. In what you provided above, 'enabled' and 'email' are at the same level. You have no values under 'enabled'. Again, look at the docs to see the proper format.

@jdsika I'll see what I can do, but I'm struggling on how to explain it better.

**Comment by rzup** [comment]
I did check the documentation before but didn't understood you have to put the email under enabled and then below put email again for the config. Got it working now, I'm sorry for your trouble and thank you for the help.
