### ISSUE TITLE
gas exhausted operation

### ISSUE THREAD

**Issue by Primate411** [tezos-reward-distributor-organization/tezos-reward-distributor#352]
**Describe the bug**
Paying cycle 309 resulted in an error. This is the first payment for delegator [](https://tzstats.com/KT1UcPh3S1K1GAFqUt212H9qjFVdxEnca1qk)

Actual error:
Error while validating operation - Status: failed, Message: proto.007-PsDELPH1.gas_exhausted.operation

**To Reproduce**
Running the following command which is what I usually run to pay frozen cycles.
[app_verbose_309_20201223_204000.log](https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/files/5740967/app_verbose_309_20201223_204000.log)

python3 src/main.py -E ~/tezos -M 3 -C 309 -R -5 -P tzstats -V on

Using default fee.ini or using fee.ini from last rev in January.

**Expected behavior**
The fee automatically calculates properly to be included in baking but not be too high to be wasteful.

**Screenshots**
N/A

**Environment**
 - Latest source coce
 - Attached configuration (note: API info removed, attached as text
[tz1S5WxdZR5f9NzsPXhr7L9L1vrEb5spZFur.txt](https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/files/5740971/tz1S5WxdZR5f9NzsPXhr7L9L1vrEb5spZFur.txt))
 - Mainnet
 - python3 src/main.py -E ~/tezos -M 3 -C 309 -R -5 -P tzstats -V on
 - Ubuntu 20.10

**Additional context**
N/A

Thank you

**Comment by Primate411** [comment]
I got around this problem for now by redirecting the KT1's rewards to its manager tz1 address.  So far 2 cycles this way no problem.

**Comment by jdsika** [comment]
We will make this redirect most likely the default behavior and bundle those transactions belonging to the same manager tz

**Comment by jdsika** [comment]
fixed with #353
