### ISSUE TITLE
QuipuSwap baker rewards distribution support

### ISSUE THREAD

**Issue by lourenc** [tezos-reward-distributor-organization/tezos-reward-distributor#366]
**Is your feature request related to a problem? Please describe.**
We at the QuipuSwap team would like to ensure TRD is able to distribute rewards for QuipuSwap. There's no problem, but it hasn't been properly tested with TRD yet :)

**Describe the solution you'd like**
Currently, we have implemented  `default` entrypoint on each `Dex` (exchange pair `tokenA-XTZ`) contract, and all the funds sent there are being distributed as baker rewards to the users who invested their liquidity. We're using specific mechanics for the distribution of the rewards based on the user share in the pool over a period of time. 

[More information on it here](https://docs.quipuswap.com/baker-rewards)

Important to note that the baker for each `Dex` is selected separately via the on-chain governance taking into account users' votes on that specific pool. 

As far as we understand, the current TRD version is able to send rewards to `default` entrypoint of `KT1` addresses, but it would be great to double-check it.

**Additional context**
To actually vote for the baker on the QuipuSwap, you have to:

1) Put liquidity into QuipuSwap by navigating to https://quipuswap.com/invest/add-liquidity and selecting the desired pair, amount to be invested, and clicking the `Add Liquidity` button. After this step, you'll obtain the shares of that liquidity pool in the form of either FA1.2 or FA2 token depending on the pool type.

2) Then go to `Governance` section, select the token pool you have invested liquidity to, and type in desired amount of shares to vote with and the address of the desired baker in the "Vote for baker" form. 

![image](https://user-images.githubusercontent.com/6189971/106892911-6e63ff80-66f5-11eb-80f2-8f23a52296cc.png)

3) After this if voting is successful and there were no other bakers selected, the pool funds are going to be delegated to the baker you've voted for.

4) Reward in the protocol is distributed to the users over the 30 days period.

**Comment by amzid** [comment]
The current TRD version should even take care of sending the rewards directly to the liquidity providers based on their share in the total liquidity pool balance. But if I understood you right, this is already taken care of in the Dex contract script. Based on this, we only need to check that the currently set limits for the fees are enough to perform the payment to the smart contract. You can ping me with a private message and we can perform a dry run to check if everything is working as expected.

**Comment by jdsika** [comment]
@amzid very important for v9.0

**Comment by amzid** [comment]
If I am not mistaken, I did not get any input yet.

**Comment by jdsika** [comment]
@lourenc please delegate a contract to the edo2net baker with the maximum complex case of usage of that contract for amzid to test:

tz1dAfFc4QAre74yrPU2jFBLcgaAs9MLHryD

**Comment by lourenc** [comment]
Hi @amzid and @jdsika . I'm sorry for such a late reply on this! 

We have deployed FA1.2 QuipuSwap Factory with Dex and triggered the "vote" entrypoint on the contract for delegation to the address at `tz1dAfFc4QAre74yrPU2jFBLcgaAs9MLHryD`. Here's the link to the delegation operation: https://edo2net.tzkt.io/ookhHAs2UGjiedwgdAVkhoXwGDFVCgUiXMphMXj1RskdEVwtoc8/8921/2

Please, let me know if that baker address is still relevant for testing purposes.

P.S. We're also currently reviewing QuipuSwap's baker rewards distribution algorithm - there's a high chance of us making changes in that part of code during the next week.

**Comment by jdsika** [comment]
@lourenc did you close as everything is working fine or because there was no reply. We have been quite busy with "real life" but intend to make release now
