### ISSUE TITLE
hDAO staking rewards

### ISSUE THREAD

**Issue by crzypatchwork** [tezos-reward-distributor-organization/tezos-reward-distributor#367]
We'd like, if possible, to test the tezos rewards distributor for a hDAO KT on a delphi/edo baker. Would there be any tz address for which we can delegate?

Sample Contract: https://better-call.dev/delphinet/KT18jV9kZzFN5PvxmVbQ8S6eqvQYfaTogd6H

**Comment by jdsika** [comment]
Could you please give a short specification.
Intended functionality
What is the TRD expected to do? Payout to contract, read something from the storage and pay to tz manager?
If we have a good understanding of it we can test on the weekend

**Comment by crzypatchwork** [comment]
the idea is that 730k xtz max would be stored in the present version of the contract. we would like to select a baker which possibly uses the tezos reward distributor for such test. we have configured a default entrypoint with unit parameters for receiving transactions. payment should be sent directly to the KT address, there being two vaults, one determined by the balance variable at the kt storage, and an internal one which concerns the total balance of the KT.

**Comment by jdsika** [comment]
Use this Bootstrap baker for test delegations: tz1dAfFc4QAre74yrPU2jFBLcgaAs9MLHryD

**Comment by crzypatchwork** [comment]
Is it on edonet? I'll provide a contract address for such network in a second.

**Comment by crzypatchwork** [comment]
kt address
```KT1WC6Srf1e6r3DWPMmhvxE9BqtGZUv9Eyfb```

op
```
{'chain_id': 'NetXSp4gfdanies',
 'hash': 'ooRWcoiJdsdZfnZoYmYdH9RY9meXvuJ94Jv5wvHcNkKA2PE3y9e',
 'protocol': 'PtEdoTezd3RHSC31mpxxo1npxFjoWWcFgQtxapi51Z8TLu6v6Uq',
 'branch': 'BMPfjHaE6aJg7v9s5y4b7eQUoWE4BfYiiCPVB4VrkkdV4jALwyB',
 'contents': [{'kind': 'transaction',
   'source': 'tz1UBZUkXpKGhYsP5KtzDNqLLchwF4uHrGjw',
   'fee': '2468',
   'counter': '114172',
   'gas_limit': '21570',
   'storage_limit': '0',
   'amount': '0',
   'destination': 'KT1WC6Srf1e6r3DWPMmhvxE9BqtGZUv9Eyfb',
   'parameters': {'entrypoint': 'set_baker',
    'value': {'string': 'tz1dAfFc4QAre74yrPU2jFBLcgaAs9MLHryD'}}}],
 'signature': 'sigapucqBqxE5EmERUyfDaKHyMeSHRcwYAFQFskGdBkRd28GjbXjV7gcjsBTVh3EDPAxyWhvbYJczi9BSsdDPYZoB2Q97Me2'}```

**Comment by crzypatchwork** [comment]
I'll be following along to see what happens

**Comment by jdsika** [comment]
@amzid focus topic!

**Comment by jdsika** [comment]
@crzypatchwork the edonet was reset due to the emergency patch. I think you have to re-delegate. The testing is now harder. Please ping amzid via baking slack for questions

**Comment by crzypatchwork** [comment]
I imagined that this could have happened from the emergency path. I tried to delegate again but the operation was refused. I'll try again with another contract during this week.

**Comment by crzypatchwork** [comment]
I was reading in another issue that staking rewards could be as well be calculated and sent proportionally to someone tz holdings?

**Comment by jdsika** [comment]
@crzypatchwork If your KT contract has a default entry point the delegation is working and the payments are calculated properly with #411
