### ISSUE TITLE
Issue with TRD after the last update 

### ISSUE THREAD

**Issue by lexxor79** [tezos-reward-distributor-organization/tezos-reward-distributor#371]
![image](https://user-images.githubusercontent.com/36721985/107857209-3cf1df00-6e2d-11eb-8e53-2d55f3fe5e04.png)

**Describe the bug**
Error message "please make sure you have started the signer using" while starting Tezos Reward Distributor with KILN
Tried to do it with signer

**Comment by jdsika** [comment]
Can you try a different port for the signer, please?

**Comment by amzid** [comment]
Did you import the secret key of tz1aq... to the signer? The log from the signer suggests that no keys are found for that address

**Comment by jdsika** [comment]
Yes, the error message does also instruct to do this. I will close this.

**Comment by lexxor79** [comment]
Hello, 
Sorry for the inconveniance but still not able to make it back to work...

I have correctly imported the secret key tz1aq.... without using Alias as I read somewhere that Alias are not handle anymore.
Replace the Alias from cfg file by the public key.

![image](https://user-images.githubusercontent.com/36721985/108055543-69397580-7050-11eb-9847-f570edb4651b.png)

Started the Tezos Signer with the good port
![image](https://user-images.githubusercontent.com/36721985/108056622-c7b32380-7051-11eb-9591-88aa9aaa7a8b.png)

Then Start back TRD :
![image](https://user-images.githubusercontent.com/36721985/108056756-ff21d000-7051-11eb-851e-6ecf5f1714e9.png)

But still this error message...
