### ISSUE TITLE
Insurance policy payout option

### ISSUE THREAD

**Issue by Xelendor1** [tezos-reward-distributor-organization/tezos-reward-distributor#374]
**Is your feature request related to a problem? Please describe.**

Delegators are frustrated when our baker misses endorsements/block and would like some sort of insurance policy.

**Describe the solution you'd like**

We would like an option to pay out the difference between actual rewards and optimum rewards(not including priority 1 blocks/endorsements).  In turn we would raise our fee by 5% and pay this to an "insurance" wallet where we would pay missed rewards from(due to network malfunction/baker mistakes).

This solution would create a separate transaction, say "insurance payout for missed rewards" and have the option to use a different private key to make the payment.

**Describe alternatives you've considered**

Baking bad has a temporary solution, however it is rather expensive and doesn't justify the cost to the baker, when in actuality it is just helping the delegators.  Many small bakeries don't make enough profit to even thing about talking to a third party.

**Additional context**

**Comment by utdrmac** [comment]
You can simply create another tz1 address and specify this address in your TRD config as an `owner` which receives 1% of baker reward. That will end up being like a "savings account".

> pay out the difference between actual rewards and (ideal) optimum rewards

Can you explain this in more detail?

**Comment by jdsika** [comment]
Dear @Xelendor1 we have added the "insurance payout policy" in #415 from the Backerei tool. Please have a look at the discussion there and especially at the description of the new policy "ideal" (ATTENTION THERE WAS A RENAMING: old "ideal" is now "expected"). Feel free to reopen the issue if you feel not satisfied with the solution.
