### ISSUE TITLE
Issue with the new release of TRD used with Kiln node

### ISSUE THREAD

**Issue by lexxor79** [tezos-reward-distributor-organization/tezos-reward-distributor#376]
Hello,

Sorry for the inconvenience,
The previous bug report have been closed but still have the same issue :
After Updating KILN according to Edo upgrade and TRD to the new version, I'm having issue to start back TRD and pay delegators.

I have successfully re-imported the secret key tz1aq.... without using Alias as I read somewhere that Alias are not managed anymore.
![image](https://user-images.githubusercontent.com/36721985/108058453-5a54c200-7054-11eb-8c5e-00bfd9f1cfce.png)

I have followed this instruction to change the KILN port to 8732 :
https://gitlab.com/obsidian.systems/kiln/-/blob/develop/docs/distros/ubuntu.md#configuring-the-ubuntu-package
Started the Tezos Signer with the good KILN port (8732)

Started the signer using :
![image](https://user-images.githubusercontent.com/36721985/108058716-b61f4b00-7054-11eb-8c72-0e946eccff59.png)

And then started back TRD program :
![image](https://user-images.githubusercontent.com/36721985/108058996-2037f000-7055-11eb-92a8-f056578618df.png)

But I still have the same issue...

Can you help me ?
Thank you !

**Comment by habanoz** [comment]
Check two things, please.
- Private key should be imported to the signer. Importing to the client is not enough. 
- From the images, I see the same terminals are being used. Make sure tezos signer is not shut down before starting the trd. You may use two seperate terminals at the same time, one for signer, one for trd.

**Comment by lexxor79** [comment]
Thanks for your reply :)
First, I don't understand because I never had to start the signer using Kiln before.
Is it due to the last TRD version ?
When i do  ./tezos-client list known addresses I see that my key is well imported.
I'm also using two different terminals.

**Comment by habanoz** [comment]
> I'm also using two different terminals.
Good.

> When i do ./tezos-client list known addresses I see that my key is well imported.
Signer and tezos-client are two different applications. I am not sure importing to the client is enough. Please try to execute the following command, you should be able to see your payment address.

`tezos-signer list known addresses `

> Is it due to the last TRD version?
In past, trd was delegating signing to the client. Now trd makes direct signer calls. 

Regards

**Comment by jdsika** [comment]
@lexxor79 please always look at the changelog in the release notes and read the accompanying agora posts. We answer those questions there. If then still things are unclear (also very likely) open an issue. In this case your issue e.g. delays the release as we are naturally on alert if we see a bug report and investigate before doing a new release.

**Comment by jdsika** [comment]
I will close this. Feel free if you think it is a bad description in the docs (pull master for this)
