### ISSUE TITLE
 Unknown error in payment producer loop: 'str' object has no attribute 'isIdeal', will try again.

### ISSUE THREAD

**Issue by habanoz** [tezos-reward-distributor-organization/tezos-reward-distributor#381]
Exception occurs at the line below:

expected_rewards = expected_rewards or self.rewards_type.isIdeal()

rewards_type is of type 'str' thus has no 'isIdeal' method.

**Comment by utdrmac** [comment]
Can you share your .yaml conf? I'm unable to reproduce this.

**Comment by habanoz** [comment]
baking_address: tz1TRspM5SeZpaQUhzByXbEvqKF1vnCM2YTK
delegator_pays_xfer_fee: true
rewards_type: actual
founders_map: {KT18bVwvyLBR1GAM1rBoiHzEXVNtXb5C3vEU: 0.15, KT18ie6fHZcK62e46p67VyJCsNSLAp3ntXH3: 0.85}
min_delegation_amt: 10.0
owners_map: {KT18bVwvyLBR1GAM1rBoiHzEXVNtXb5C3vEU: 0.15, KT18ie6fHZcK62e46p67VyJCsNSLAp3ntXH3: 0.85}
payment_address: tz1Z1tMai15JWUWeN2PKL9faXXVPMuWamzJj 
rules_map: {
KT1CsKsmqVWmnFSiQkZt5c3pgMbzYX2okWvi: TOB, KT1VFrVbFaK9YUy8ZDj49XmFkB3ZwvZeZTqi: KT18bVwvyLBR1GAM1rBoiHzEXVNtXb5C3vEU, KT18ie6fHZcK62e46p67VyJCsNSLAp3ntXH3: TOB, mindelegation: TOF}
service_fee: 7.0
specials_map: {KT1GADSzdPnCVwjaLithz3kQoaMxdgcdiRsB: 23.3}
supporters_set: !!set { KT1RDuVQUusQmwM1iphJjg3QHikZcvWNb8bg: null}
reactivate_zeroed: False
delegator_pays_ra_fee: False
plugins:
  enabled: []

**Comment by jdsika** [comment]
@utdrmac can you resolve this until friday for the release?

**Comment by utdrmac** [comment]
@jdsika I can't reproduce it. I tried using the same config as above and it works for me.

**Comment by jdsika** [comment]
ok, then I will close it...
