### ISSUE TITLE
Transaction backtracked

### ISSUE THREAD

**Issue by NeoktaLabs** [tezos-reward-distributor-organization/tezos-reward-distributor#383]
**Describe the bug**
I am running my archive node built from sources in version 8.2 (latest-release).
I am running TRD (latest version).
My payment reports are saying that the payment have been done successfully (I can see the report sent by email reporting no issues).
However; the transactions failed and I can see that some are "Backtracked" and some are "Skipped"
See the operation here: https://tzstats.com/ooMhyNiPvPUbFDRYu8CGSKHa54QrgvKBFn4iWdouzMt42HBSsL2

**Expected behavior**
Transactions to be successfully sent, and not "skipped" or "backtracked"

**Screenshots**
See : https://tzstats.com/ooMhyNiPvPUbFDRYu8CGSKHa54QrgvKBFn4iWdouzMt42HBSsL2

**Environment**
 - Archive node built from source
 - See TRD yaml attached
 - Mainnet
 - TRD service via : python3 src/main.py -V on and sudo python3 service_add.py -f ~/pymt/cfg
 - Ubuntu Server

**Additional context**
I have TRD version 7.5 on my secondary node and payments for the same cycle with the same YAML conf file were successful. No issues with 7.5

![2021-02-21 20_58_45-tezos@jga-baker3_ ~_pymnt_cfg](https://user-images.githubusercontent.com/74187584/108636795-e9643e80-7487-11eb-8bbc-bc63ece49ee1.png)

**Comment by NeoktaLabs** [comment]
I just pulled the latest from master branch but I got the same issue this morning.
Everything goes well on TRD side; no issues on the verbose logs. But the transactions keep being backtracked.
Here is the backtracked operation this morning: https://tzstats.com/opQ3q2aaD3s2J6nvsLpFbU2QNfeBTB3XD3nX48X1id8zMiCfnpH

Thanks

**Comment by jdsika** [comment]
Did you use a higher fee? I had reports that the fees are not enough anymore due to the higher activity on the chain. Also do another git pull as I just merged another PR

**Comment by NeoktaLabs** [comment]
I did not change my fees; still 5%
I have used TRD 7.5 this morning to send our rewards. No problems at all. I really never had any issues with 7.5
I will git pull again and give it another try at next cycle. I will update the issue. Thanks

**Comment by jdsika** [comment]
I meant the "transaction fees" in fee.ini. But the observation that it did work with 7.5 can either be coincident because at the second attempt the network was not crowded OR it is systematic @utdrmac ?

**Comment by NeoktaLabs** [comment]
When I look at the operation hash; both https://tzstats.com/opQ3q2aaD3s2J6nvsLpFbU2QNfeBTB3XD3nX48X1id8zMiCfnpH and https://tzstats.com/ooMhyNiPvPUbFDRYu8CGSKHa54QrgvKBFn4iWdouzMt42HBSsL2 we can see that transactions are "skipped" and the 1st one to be "backtracked" refers to an account with exactly 0 XTZ balance. Could it be linked?

On operation hash https://tzstats.com/ooMhyNiPvPUbFDRYu8CGSKHa54QrgvKBFn4iWdouzMt42HBSsL2 , the 1st transaction to be backtracked refers to the following account: https://tzstats.com/tz1TNKE9udiqvcxUeUpHqVAZcevtAdCxWgqQ

On operation hash https://tzstats.com/opQ3q2aaD3s2J6nvsLpFbU2QNfeBTB3XD3nX48X1id8zMiCfnpH , the 1st transaction to be backtracked refers to the following account: https://tzstats.com/tz1aNydK9B3a8ZaKcgDC7kvnMBpGP8W3FuSV

And I searched online; and an history issue were raised regarding backtracked operqtion, and it was something to do with 0 balance accounts; see here: https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/issues/159

Thanks

**Comment by utdrmac** [comment]
@NeoktaLabs Absolutely correct. The issue with your payouts is due to the delegator with 0 balance. The quickest way to move forward is to disable reactivate_zeroed in the config. This will skip payouts to anyone with a current 0 balance. TRD should be handling this and will require some investigation.

**Comment by NeoktaLabs** [comment]
@utdrmac Thanks for your answer. As you can see in my config file above, the reactivate_zeroed is already set to false which is why it confuses me.

**Comment by sombriodasilva** [comment]
I also would like to know about any update. I had a similar problem yesterday in this transaction:
https://tzkt.io/oojgozZz9WgceYBHmhhe9tje4SXEKoAXu1Repba5qLZGnLMwREg

**Comment by jdsika** [comment]
That SHOULD have been resolved in #411 - I will close this issue and you feel free to reopen if it still occurs. Play around with the reactivate_zero option and tell if it works

**Comment by nurikabe** [comment]
Pretty sure this is still an issue. I've noticed that if regular `D` delegators have a zero balance, payment is skipped and a "Excluded by zero balance." note is logged.

However if the recipient with a zero balance is in the owners or founders map then the batch still gets backtracked.
