### ISSUE TITLE
Consider compressing verbose logs with gz

### ISSUE THREAD

**Issue by utdrmac** [tezos-reward-distributor-organization/tezos-reward-distributor#385]
@habanoz Compressing verbose logs with zip requires manual decompression each time you want to view a log file. This is a painstaking process when you're trying to find a problem.

If the logs were compressed with gz, then native linux tools like 'zless', 'zgrep' can be used to read and search the logs without requiring a manual step to decompression.

**Comment by habanoz** [comment]
@utdrmac I would be happy to move to gz. However, to my knowledge, zgrep and less supports zip files. Would you mind trying and providing feedback.

Regards

**Comment by utdrmac** [comment]
Nope.

```
$ zip foo.zip ~/Desktop/baked_block.txt
  adding: /Users/utdrmac/Desktop/baked_block.txt (deflated 77%)

$ zless foo.zip
PK^C^D^T^@^@^@^H^@MdWQJ<8E><AC><8E><F1>^Z^@^@^Su^@^@#^@^\^@Users/utdrmac/Desktop/baked_block.txtUT        ^@^C!^T<93>_!^T<93>_ux^K^@^A^D<F5>^A^@^@^D^T^@^@^@<EC>\َ
<A3>X<B6>}<8F><AF><B0>⡺Z<CA>!<98>!t<EB><96>0<93><9B><A9><CD>d<86>R)<C5><^E<83><99><A1><95><FF>~<89>HgVT<A7><AB>U<CE>ESCYjY<C1>^S<86><B3><E1><B0><D6>><E7>l<D6>ކ
```

**Comment by habanoz** [comment]
@utdrmac It looks like there are environmental differences. In my test environment (Ubuntu 18.04.1 LTS), it works with 'zless'. I sent a PR to work with gzip format. Please review.

https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/pull/387
