### ISSUE TITLE
Transactions lost in mempool

### ISSUE THREAD

**Issue by akrykunenko** [tezos-reward-distributor-organization/tezos-reward-distributor#388]
**Describe the bug**
4 batches out of 8 were "Lost in the mempool" as per tzkt.io
Probably, the current fee specified in the `fee.ini` file was not enough for operations to be included and they were lost (not included).
The issue is that in the TRD `/payments/done/` report they are marked as `paid = 3`. This means that there is no `/payments/failed/` file so I can't retry it with `-M 4` flag.

**To Reproduce**
1. Run TRD as usual when the network is high loaded a bit (or with low fees)
2. Verify that operation was "Lost in the mempool"

**Expected behavior**
It seems that TRD should verify that transaction was actually included in the blockchain before marked it as `paid`.

**Screenshots**
N/A

**Environment**
 - Source Code Build
 - N/A
 - Mainnet
 - `python3 src/main.py -C 332 -P tzkt -M 3`
 - Ubuntu 18.04 LTS

**Additional context**
The other thoughts are that the default fee in the `fee.ini` file might be not enough anymore due to the NFT hype.

**Comment by habanoz** [comment]
Status 3 means, a batch is injected but no success response is received.  In this case, TRD leaves the responsibility to the baker to decide if payment has happened or not. If it did not happen, you can use "-inj" flag to retry. Another option is manually setting lines to failed ("0").  Make sure the payment report is under failed reports directory.

**Comment by dansan566** [comment]
@habanoz So the baker has two options if I understand you correctly?
1) `python3 src/main.py -C 332 -P tzkt -M 3 -inj` without moving the CSV file from done into failed?
or 
2) `python3 src/main.py -C 332 -P tzkt -M 4` if failed ops are set to 0 and moved into failed?

**Comment by habanoz** [comment]
In both cases, the payment report should be under the "fail" directory. 

Running mode is not very important. By default, TRD retries failed payment at all modes. Mode 4 is specifically for retrying. 

If option "-inj" is given, payments in status 3 are automatically set to status 0 before retry. 

Hope this clarifies.
