### ISSUE TITLE
batch_payer.py error upon payment

### ISSUE THREAD

**Issue by Primate411** [tezos-reward-distributor-organization/tezos-reward-distributor#391]
**Describe the bug**
Payment for cycle 339 fails with batch_payer.py error.

2021-03-20 12:49:32,168 - consumer0 - Payment to KT1HCVyrTZJcYnR7aF9bmxmaWboHXqj2rC8G script requires higher fees than reward amount. Skipping.

**To Reproduce**
python3 src/main.py -E http://127.0.0.1:22000/ -M 3 -C 339 -R -5 -P tzkt -V on

**Expected behavior**
Payment succeeds without error

**Screenshots**
N/A

**Environment**
 - Latest version, just did git pull
 - Attached configuration
 - Chain mainnet
 - actual command used above
 - Operating system / system specification: Ubuntu 20.04

**Additional context**
Ledger payment

[tz1S5WxdZR5f9NzsPXhr7L9L1vrEb5spZFur.yaml.txt](https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/files/6176017/tz1S5WxdZR5f9NzsPXhr7L9L1vrEb5spZFur.yaml.txt)
[app_verbose_339_20210320_124923.log](https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/files/6176018/app_verbose_339_20210320_124923.log)

**Comment by Primate411** [comment]
Trying to up the fee didn't help

**Comment by Primate411** [comment]
Looks like my payments have been partially failing since 336 where the KT1 addresses from new Kolibri ovens were being skipped. Since 339 it's failing altogether.

**Comment by dansan566** [comment]
We are currently looking into it!

**Comment by Primate411** [comment]
The fix-liquidated-ovens branch resolved my issue. There are no problems with fees for other ovens either. Thank you!

**Comment by Primate411** [comment]
[app_verbose_340_20210324_153219.log](https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/files/6200085/app_verbose_340_20210324_153219.log)
Successful run verbose output
