### ISSUE TITLE
Delegated Based Offering - Continuous Delegated Offering

### ISSUE THREAD

**Issue by bmaisseu** [tezos-reward-distributor-organization/tezos-reward-distributor#397]
I would like to know if a feature allowing to pay the reward to the delegator with a FA1.2 token would be possible to implement.
Indeed, as we have described in the following draft white paper (link below + pdf attached), we would like to use this functionality to achieve a coin offering, allowing a new kind of Delegated Based Decentralized Finance.

http://werenode.com/blog-list.html

Thanks in advance for you help.

[WerenodeWhitepaperv09 (7).pdf](https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/files/6211471/WerenodeWhitepaperv09.7.pdf)

**Comment by jdsika** [comment]
Is there a timeline for when the support is needed? I will have a look into it personally

**Comment by bmaisseu** [comment]
Hello Carlo,
thanks for your answer. I am struggling to build the concept as functional for the end of May, though there are still many components missing (baking structure, reward with coin emission (hence TRD), but also the DEX (though we have a proto for this), DAO and buy back (and/or burn) smart contract (this one is very tricky because the algorithm shouldn’t be linear). The two later being the most complicated we might begin without full automation on this. Anyway it would be great to be able to have a TRD enhancement with this target date in mind (I have really no idea of the amount of work that this needs). For the baking, it’s something that we could discuss when you have some time available.
Kind regards,
        B.

**Comment by jdsika** [comment]
After quite some discussions we had offline I am closing this issue as we have decided that this is a feature that must be put into a smart contract.
