### ISSUE TITLE
Broken Unit Test

### ISSUE THREAD

**Issue by habanoz** [tezos-reward-distributor-organization/tezos-reward-distributor#404]
**Describe the bug**
A unit test is broken. Needs to be fixed.

**To Reproduce**
1. Go to test/test_tzkt_api.py
2. Rename disabled_test_dry_run to test_dry_run
3. Run the test

**Expected behavior**
The test seems to be important. It checks details about payment calculations.

**Screenshots**
![image](https://user-images.githubusercontent.com/6825980/113202476-76fb3100-9273-11eb-89e2-a90b4b2a06a8.png)

**Comment by jdsika** [comment]
I am closing this as I think it has been solved. @vkresch reopen if it was a mistake
