### ISSUE TITLE
Tezos payout data unable to fetch?

### ISSUE THREAD

**Issue by SachinSWN** [tezos-reward-distributor-organization/tezos-reward-distributor#406]
`ubuntu@ip-172-31-46-41:~/tezos-reward-distributor$ sudo systemctl status tezos-reward.service
● tezos-reward.service - Tezos Reward Distribution Service
   Loaded: loaded (/home/ubuntu/tezos-reward-distributor/tezos-reward.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Mon 2021-04-05 12:12:28 UTC; 10min ago
     Docs: https://tezos-reward-distributor-organization.github.io/tezos-reward-distributor/
  Process: 12156 ExecStop=/usr/bin/python3 /home/ubuntu/tezos-reward-distributor/src/stop.py (code=exited, status=0/SUCCESS)
  Process: 8401 ExecStart=/usr/bin/python3 /home/ubuntu/tezos-reward-distributor/src/main.py -s -D -C 321 -M 2 (code=exited, status=0/SUCCESS)
 Main PID: 8401 (code=exited, status=0/SUCCESS)

Apr 05 12:12:27 ip-172-31-46-41 python3[8401]:   magic byte 0x03 not allowed
Apr 05 12:12:27 ip-172-31-46-41 python3[8401]: '
Apr 05 12:12:27 ip-172-31-46-41 python3[8401]: 2021-04-05 12:12:27,029 - consumer0 - Payment of batch 1 is complete, in 3 attempt(s)
Apr 05 12:12:27 ip-172-31-46-41 python3[8401]: 2021-04-05 12:12:27,029 - consumer0 - Processing completed for 4 payment items, 4 failed.
Apr 05 12:12:27 ip-172-31-46-41 python3[8401]: 2021-04-05 12:12:27,030 - consumer0 - Payment report is created at '/home/ubuntu/tezos-reward-distributor/reports/tz1h
Apr 05 12:12:27 ip-172-31-46-41 python3[8401]: 2021-04-05 12:12:27,030 - consumer0 - [Plugins] Not sending notification; no plugins enabled
Apr 05 12:12:27 ip-172-31-46-41 python3[8401]: 2021-04-05 12:12:27,030 - consumer0 - Exit signal received. Terminating...
Apr 05 12:12:27 ip-172-31-46-41 python3[8401]: 2021-04-05 12:12:27,030 - consumer0 - Consumer returning ...
Apr 05 12:12:28 ip-172-31-46-41 python3[12156]: Stopping reward distributor
Apr 05 12:12:28 ip-172-31-46-41 python3[12156]: No lock file. No running process
`

**Comment by habanoz** [comment]
> "magic byte 0x03 not allowed" 

Looks like a signer error. Could you please make sure that your signer is configured properly?
