### ISSUE TITLE
Validate Baking Address

### ISSUE THREAD

**Issue by habanoz** [tezos-reward-distributor-organization/tezos-reward-distributor#410]
**Is your feature request related to a problem? Please describe.**
TRD validates payment addresses by checking if signer has the private key. However, there is no such validation for baking address.

**Describe the solution you'd like**
TRD should check if the baking address is a valid address at application launch and provide a clear description of what is not correct.

**Describe alternatives you've considered**
Validation logic may contain the following checks:
- Is the address present at all?
- Is the address enabled for delegation?

**Why does TRD need to validate baking address?**
I believe if the baking address is not correct, it should fail during launch. Trying to understand why an RPC request is failing would be harder.

**Comment by utdrmac** [comment]
Why does TRD need to validate baking address?

**Comment by habanoz** [comment]
The discussion can be found here: https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/pull/405#issuecomment-815076473

I believe if the baking address is not correct, it should fail during launch. 

Trying to understand why an RPC request is failing would be harder.

**Comment by utdrmac** [comment]
```
http://127.0.0.1:9731/chains/main/blocks/head/context/contracts/tz1KqTpEZ7Yob7QbPE4Hy4Wo8fHG8LhKxZSx/manager_key
<<<<1: 200 OK
{ "manager": "tz1KqTpEZ7Yob7QbPE4Hy4Wo8fHG8LhKxZSx",
  "key": "edpkuBknW28nW72KG6RoHtYW7p12T6GKc7nAbwYX5m8Wd9sDVC9yav" }
```

> Here, the key field contains a public key, which means a revelation operation has already been published.

https://www.ocamlpro.com/2018/11/15/an-introduction-to-tezos-rpcs-a-basic-wallet/
