### ISSUE TITLE
trd is not working properly after latest update?

### ISSUE THREAD

**Issue by SachinSWN** [tezos-reward-distributor-organization/tezos-reward-distributor#412]
2021-04-08 12:25:30,663 - consumer0 - Command failed, error is |Warning:  the --addr --port --tls options are now deprecated; use --endpoint instead

**Comment by jdsika** [comment]
It just means that one of the RPCs used is no longer supported (deprecated) and will be removed in the future. To my knowledge it still works and reminds You to change it. Thank you for reporting we will put this on the agenda.

**Comment by utdrmac** [comment]
@SachinSWN Yes, it's just a warning. TRD is working fine.

**Comment by SachinSWN** [comment]
above error happens to older version, if i ugrade it into latest one, i get this error

**Comment by SachinSWN** [comment]
> @SachinSWN Yes, it's just a warning. TRD is working fine.

`2021-04-08 13:26:11,498 - consumer0 - batch payment attempt 1/3 for current batch failed with error
Traceback (most recent call last):
  File "/home/ubuntu/tezos-reward-distributor/src/pay/batch_payer.py", line 190, in pay_single_batch
    status, operation_hash = self.attempt_single_batch(payment_items, op_counter, verbose, dry_run=dry_run)
  File "/home/ubuntu/tezos-reward-distributor/src/pay/batch_payer.py", line 326, in attempt_single_batch
    signed_bytes = self.wllt_clnt_mngr.sign(bytes, self.manager_alias, verbose_override=True)
  File "/home/ubuntu/tezos-reward-distributor/src/cli/simple_client_manager.py", line 38, in sign
    raise ClientException("Error at signing: '{}'".format(response))
exception.client.ClientException: Error at signing: 'Warning:  the --addr --port --tls options are now deprecated; use --endpoint instead
Error:
  magic byte 0x03 not allowed
`

**Comment by utdrmac** [comment]
@SachinSWN Please read the error message in what you just posted:

`Please make sure you have started the signer using "./tezos-signer launch http signer"`

You are not using http signer.

**Comment by utdrmac** [comment]
>  Error: magic byte 0x03 not allowed
@SachinSWN That is not a TRD error. That is a tezos-signer error. You do not have signer properly configured.

**Comment by SachinSWN** [comment]
> @SachinSWN Please read the error message in what you just posted:
> 
> `Please make sure you have started the signer using "./tezos-signer launch http signer"`
> 
> You are not using http signer.

my siner node is already running for a long time, are u recommending, i need to stop that and restart the signer node again

**Comment by utdrmac** [comment]
I don't know what "signer node" is. There is tezos-node, and tezos-signer. We are not talking about tezos-node. Your signer must be properly configured to be running in http mode (which yours is not, I see tcp:// in the error you pasted), and you must not have watermark restrictions on transfers (0x03)

**Comment by SachinSWN** [comment]
> I don't know what "signer node" is. There is tezos-node, and tezos-signer. We are not talking about tezos-node. Your signer must be properly configured to be running in http mode (which yours is not, I see tcp:// in the error you pasted), and you must not have watermark restrictions on transfers (0x03)

For almost 6months it was working fine with 'tcp', itself, after the feb 2 upgrade, it showing this error..neither older version is working nor the latest version

**Comment by utdrmac** [comment]
If old TRD is not working, and new TRD is not working, then absolutely there is an issue on your side and not with TRD.

**Comment by jdsika** [comment]
@SachinSWN we are making a lot of effort in communicating the changes of TRD to the community. Please always read the changelog and release notes and also the posts on Tezos Agora. Maintaining this software is "our hobby" and we have to rely on the users and the community behind the tool to "own" this tool as much as we do. Reading the error messages and following the instructions is expected. We place those instructions by intention to help the community to solve those issues themselves.
