### ISSUE TITLE
fee of 512 too low for just one payout

### ISSUE THREAD

**Issue by nicolasochem** [tezos-reward-distributor-organization/tezos-reward-distributor#430]
**Describe the bug**
When the delegate has only one delegator for a cycle, the operation is never included. Increasing the fee to 1512 in fee.ini solves the problem. This happened with a mainnet node on version 9.1

**To Reproduce**
set up a delegate with just one delegator and observes that the payment never goes through.
I cannot even search the operation in a block explorer (tzkt), therefore is never even relayed to the chain, so the node filters it. It should be possible to replicate by generating a payout with just one transfer and the default fee.
It should be also possible to replicate with a regular baker and blacklisting everyone but one delegator, so just one payout goes out.

This does not happen to a baker with a lot of delegates (probably because the operation is batched and the total fees are higher)

**Expected behavior**
Payment included in the chain.

**Comment by amzid** [comment]
![image](https://user-images.githubusercontent.com/33556352/117962924-12c29700-b320-11eb-99b3-ecb91327cfcd.png)
This should actually calculate the required fee dynamically independently from the batch size. Can you provide the verbose log of this observation?

**Comment by jdsika** [comment]
@nicolasochem what do we do about this one?
