### ISSUE TITLE
Add skipped status + isolate failed/done

### ISSUE THREAD

**Issue by amzid** [tezos-reward-distributor-organization/tezos-reward-distributor#435]
* Mark skipped payment items as so instead of marking them as failed or done (+ add reason for skipping)
* Isolate done payments from skipped/failed ones

**Comment by jdsika** [comment]
so the "retry failed" mode on that cycle should honor the existing successful payments, not override them, only try the ones from the "failed" folder and append the successful ones to the existing log?

**Comment by jdsika** [comment]
we need to have a look at #388 as well to see if the status of injected but no positive confirmation is also handled correctly in the split of the two reports

**Comment by habanoz** [comment]
> * Mark skipped payment items as so instead of marking them as failed or done (+ add reason for skipping)
> * Isolate done payments from skipped/failed ones

I believe, it is necessary to explain why these changes are necessary? What is the problem or shortcoming here?

**Comment by amzid** [comment]
> we need to have a look at #388 as well to see if the status of injected but no positive confirmation is also handled correctly in the split of the two reports

Only FAILED payments will be under failed report. INJECTED and SKIPPED payments will be under done report to avoid confusion.



> > * Mark skipped payment items as so instead of marking them as failed or done (+ add reason for skipping)
> > * Isolate done payments from skipped/failed ones
> 
> I believe, it is necessary to explain why these changes are necessary What is the problem or shortcoming here?

The reason for the first change was explained in the PR. The reason for the second change is that many bakers found it misleading to have successful transactions under the failed report directory. So with this change there will be a split between successful and failed payment items.
