### ISSUE TITLE
Update FSM Diagrams for issue 435

### ISSUE THREAD

**Issue by habanoz** [tezos-reward-distributor-organization/tezos-reward-distributor#443]
PR 438 requires diagram updates. 

- A new state is introduced.
- The Payment consumer may produce two report files: success and failure report. 
- A retry fail state process diagram is missing.

**Comment by jdsika** [comment]
@vkresch I realized that the tests are using strange folders to put their temp files. E.g. there is a test drawing diagrams that put the files in the git folder directly. Those files and or folders should be part of the .gitignore file.

**Comment by vkresch** [comment]
This issue is fixed because we are currently updating the state diagram each time we make a merge into master. Thus if we encounter any new state or delete a state the diagram will be updated. Merged PR https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/pull/451
