### ISSUE TITLE
KT addresses pay commission on the network, TZ addresses do not.

### ISSUE THREAD

**Issue by SemElVik** [tezos-reward-distributor-organization/tezos-reward-distributor#444]
what is the problem?
Why do my KT addresses pay for the commission on the network, but my tz addresses do not pay it?
what has changed? from cycle 352
how can i fix it
https://baking-bad.org/KT1XVS8SYD5A3TSHg22XjBvUWdhF3UFYg77Q
https://baking-bad.org/KT1TCcxKHVbn8CVoRVqqixCFSbrK8zjd3AP1

https://baking-bad.org/tz1e2WhFEHXjrxUzTPDZNXRK1xdw8jpgYc7q
https://baking-bad.org/tz1UcWDfjBHJRctBipVVzs2L77Pu7eH8xwYX (edited) 

my settings have not changed and now they are
---------
```reactivate_zeroed : True
delegator_pays_xfer_fee: False
delegator_pays_ra_fee : True
rules_map: {tz...........: TOF}
rewards_type: actual```

**Comment by amzid** [comment]
This was originally changed in https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/commit/7381a10d99a9ac1de18cf6d3a4f01d8927768263 to avoid too high fees for KT1 addresses, but apparently the fee is always substructed from the payment amount independently from the `delegator_pays_xfer_fee` setup. Can you double check this please @utdrmac?
![image](https://user-images.githubusercontent.com/33556352/124395957-4fe74c00-dd07-11eb-8c07-ecc7662731d7.png)

**Comment by SemElVik** [comment]
Maybe I just need to increase the commission for the newsletter?  

0.000574 (tz) + 0.000873 (KT) =   0.001447 XTZ  
`fee.ini`  = 1447
it's a crutch but....

**Comment by SemElVik** [comment]
will this be fixed?

**Comment by jdsika** [comment]
Yes, Wednesday most likely

**Comment by SemElVik** [comment]
[https://baking-bad.org/KT1U6Kdd42ZW3NxY2YnVV66SdjnbccRn1Zdh](url)

the commission has been reduced, but the problem has not been resolved
