### ISSUE TITLE
Incorrect Payment Amount for Cycle 365

### ISSUE THREAD

**Issue by bakebossdev** [tezos-reward-distributor-organization/tezos-reward-distributor#445]
**Describe the bug**
My payment for cycle 365 was off by 0.000002. I believe this is because [this line](https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/blob/master/fee.ini#L7) sets the expected fee to 574 mutez, however the current fees on the network are 576 as seen in [my payout transaction](https://tzkt.io/ooFq7kDpXzmnrpVjV4uJK5q6niiRuCPxmecagpQcZezj1RPHgt8)

**To Reproduce**
1. Run TRD single-cycle payout with delegator_pays_xfer_fee set to True
2. See incorrect amounts calculated/paid

**Expected behavior**
Precise amounts are paid out to delegators.

**Screenshots**
Attached
![Mismatch](https://user-images.githubusercontent.com/22198918/122481948-a4679900-cf9d-11eb-9072-e50606982a90.PNG)

**Environment**
 - Attached configuration - 
[tz1acZQd7TdfoiUnD2czHnTHB2TaJQP6gdqo.yaml.txt](https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/files/6673591/tz1acZQd7TdfoiUnD2czHnTHB2TaJQP6gdqo.yaml.txt)
 - Chain mainnet
 - actual command used - python3 src/main.py -M 2 -A "rpcAddress" -P tzkt -E "signerAddress" -Dp -V on
 - Operating system Debian Buster

**Comment by amzid** [comment]
How did you assume that the current fees on the network are 576? A fee of 396 mutez should actually be sufficient to include an operation from a tz1 address to another tz1 address under Florence protocol.
I am not sure what is the fee assumed by baking-bad but it might be configurable?

**Comment by jdsika** [comment]
@amzid have a look at #430 maybe it is exactly beacause a sinlge payment needs the 576 and it is different with 2 transactions - not scaling lineary?
