### ISSUE TITLE
Latest update broke payouts - node.prevalidation.oversized_operation

### ISSUE THREAD

**Issue by songproducer** [tezos-reward-distributor-organization/tezos-reward-distributor#454]
```
Error, response ->[{"kind":"permanent","id":"node.prevalidation.oversized_operation","size":34358,"max_size":32768}]
<-
2021-07-20 13:54:42,091 - consumer0 - ERROR - Error in inject operation
^CException ignored in: <module 'threading' from '/Users/leotreasure/.pyenv/versions/3.8.5/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/Users/leotreasure/.pyenv/versions/3.8.5/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
```

Changed back:
MAX_TX_PER_BLOCK_TZ=200
gas_limit=3230
fee=574

and it works now.

**Comment by jdsika** [comment]
dear @songproducer thank you for the report. There was an issue in the merge process while testing a PR. The PR was tested with the value 400 and the value 600 was discussed but not tested at the same time. It was by default merged with 600. We will increase the value to 400 and also put all those "transaction related" values into the fee.ini for easy access. You can of course leave the value at 200!
