### ISSUE TITLE
Snake case for arguments

### ISSUE THREAD

**Issue by denver-s** [tezos-reward-distributor-organization/tezos-reward-distributor#465]
I find strange to use the underscore for multi-words arguments.

e.g. I'd prefer using `--dry-run` than `--dry_run`.

Is it just me? Nothing important of course, but I wondered if there's a particular reason.

**Comment by jdsika** [comment]
Let's make this discussion part of #466 and a general rework of the command line interface

**Comment by denver-s** [comment]
Functions and varibles, yes. Client arguments.... no. Python itself has `-m module-name`, `--check-hash-based-pycs mode`

**Comment by baketzforme** [comment]
Right. I was just offering a plausible explanation for why the CLI arguments are how they are. Probably just a force of habit.

**Comment by jdsika** [comment]
Guys, I will just change it to `--new-style` as I find it super annoying that it it completely wild.
