### ISSUE TITLE
Changes for Granada: e.g. blocks_per_cycle

### ISSUE THREAD

**Issue by beofor** [tezos-reward-distributor-organization/tezos-reward-distributor#467]
Sorry if it's already done or planned, but shouldn't TRD be ready for future changes in Granada's blocks_per_cycle constant (4096->8192)?
For example, as I see, level_to_cycle in *blocks_api* is just `floor(level / self.nw['BLOCKS_PER_CYCLE'])` - shouldn't it be changed to more complex rule like this: 
`if level < granada_start_level: floor (level / 4096),  else: floor((level - granada_start_level) / 8192) + granada_start_cycle `?

**Comment by jdsika** [comment]
Thank you for this - you are correct. We are currently in the progress of verifying PR #415 which is quite complex. We follow with an official release and will then do a "granada compatibility check". You could help to improve the speed greatly by looking at and testing the above mentioned PR and document all possible parts in the code in this issue where you suspect necessary changes for granada.
