### ISSUE TITLE
RPC block api problem

### ISSUE THREAD

**Issue by shibaeff** [tezos-reward-distributor-organization/tezos-reward-distributor#475]
**Describe the bug**
I'm running trd for the fresh cycle 387payouts. The trd  fails at the very beginning. 
**To Reproduce**

1. Go to your trd source folder.
2. Run the command I list below.

**Expected behavior**
I expect all the payouts for cycle 387 to happen.

**Logs output**
```
Exception in thread producer:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/root/tezos-reward-distributor/src/pay/payment_producer.py", line 128, in run
    current_cycle = self.block_api.get_current_cycle()
  File "/root/tezos-reward-distributor/src/api/block_api.py", line 18, in get_current_cycle
    return self.level_to_cycle(self.get_current_level())
  File "/root/tezos-reward-distributor/src/rpc/rpc_block_api.py", line 23, in get_current_level
    current_level = int(head["metadata"]["level"]["level"])
KeyError: 'level'
```

**Environment**
 - I'm running trd from source
 - Configuration is dead simple: just baking and payouts addresses. Other fields have default values. Commission is 9.
 - Chain: mainnet
 - Command: `python3 src/main.py -C 387 -D -V on -s -R -5 -M 3  --log-file=387.log`
 - Ubuntu 20.04
 Prior to update to v.9.0 experienced no problems

**Comment by shibaeff** [comment]
There seems to be some rpc change.
See docs for [Granada](https://tezos.gitlab.io/010/rpc.html#get-block-id-metadata) and [Florence](https://tezos.gitlab.io/active/rpc.html#get-block-id-metadata).
Field 'level' is now 'level_info'.

**Comment by shibaeff** [comment]
UPD my node desynced, restarting, there might be just problem on my side

**Comment by denver-s** [comment]
#474 should fix this issue.

**Comment by shibaeff** [comment]
Yeah, i see, didn't do full search over the branches. We severely need this granda update))

**Comment by TzBaker** [comment]
hey @jdsika, when we can expect a release to fix the payment problems? Delegators become impatient :)
