### ISSUE TITLE
Add changelog file

### ISSUE THREAD

**Issue by denver-s** [tezos-reward-distributor-organization/tezos-reward-distributor#486]
Add `changelog.rst` file, that must be updated by each merged PR.

**Comment by jdsika** [comment]
What do you think about enforcing this by following this [guideline](https://www.mokkapps.de/blog/how-to-automatically-generate-a-helpful-changelog-from-your-git-commit-messages/)?

**Comment by jdsika** [comment]
Actually @denver-s I think I will close this... I try to be as precise as possible with the squash commit messages. In addition I tag all PRs and issues with milestones and put the milestones into the Release logs
