### ISSUE TITLE
Unify -A and -Ap endpoint flags

### ISSUE THREAD

**Issue by denver-s** [tezos-reward-distributor-organization/tezos-reward-distributor#487]
RPC node's endpoint might be local or public. In any case, the format is identical.

- `http://127.0.0.1:8732`
- `https://mainnet-tezos.giganode.io`
- `https://rpc.tzkt.io/mainnet`

For `-Ap` we already check for the presence of a protocol, a domain and eventually a port number.

I propose to unify `-A` and `-Ap` to `-E --endpoint <url:port>` like Tezos does.

For simplicity, we can give alias to known endpoints:

- `-E <url:port|localhost|giganode|tzkt|tzstats|madfish>`

**Comment by jdsika** [comment]
-A is to inject the operation and -Ap is to querry data from an archive node. I think users might want to use a local node to inject the operations even when they querry data from a public node?

**Comment by ericlavoie** [comment]
> -A is to inject the operation and -Ap is to querry data from an archive node. I think users might want to use a local node to inject the operations even when they querry data from a public node?

Exactly, I do.
