### ISSUE TITLE
when RPC returns 4xx, terminate immediately, do not retry

### ISSUE THREAD

**Issue by nicolasochem** [tezos-reward-distributor-organization/tezos-reward-distributor#511]
There is a retry look in TRD RPC requests.
500 means that the server is unresponsive/down so retry is legitimate. But a 404 error means that the node does not have the requested data (it's not an archive node). In this scenario, we should exit in error, because a retry will not help.

**Comment by vkresch** [comment]
Do we want to exit all 4xx codes or only the 404 code? Currently there is already a raise ApiProviderException for 404 status codes [here](https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/blob/master/src/rpc/rpc_reward_api.py#L374) and also a general raise for all codes which are not 200 [here](https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/blob/master/src/rpc/rpc_reward_api.py#L380).

**Comment by nicolasochem** [comment]
Thanks for looking into this. I don't remember :(
It was probably not a 404, then.

Any 4xx code should raise an exception. We should only have retry loops for 5xx.
