### ISSUE TITLE
Issue with cTEZ vaults and proto.011-PtHangz2.michelson_v1.runtime_error

### ISSUE THREAD

**Issue by dansan566** [tezos-reward-distributor-organization/tezos-reward-distributor#512]
**Describe the bug**
I just did a dry run on the **newest** master branch. It seems that there are some issues with ctez vaults. First of all, I get `2021-12-04 15:00:42,222 - consumer0 - ERROR - Error while validating operation - Status: failed, Message: proto.011-PtHangz2.michelson_v1.runtime_error` and directly afterwards `2021-12-04 15:00:42,223 - consumer0 - INFO - Payment to KT18xGGaAVybAW4brVuXd7rePLSxMvDSfZdJ script could not be processed. Possible reason: liquidated contract. Skipping. Think about redirecting the payout to the owner address using the maps rules. Please refer to the TRD documentation or to one of the TRD maintainers.` The message is shown multiple times for other vaults as well. 

When looking at the contract with ctez.app, the oven looks good:
![Bildschirmfoto 2021-12-04 um 15 28 37](https://user-images.githubusercontent.com/20326784/144713209-369af61e-9467-4325-81fd-f7bd7bc4af4a.png)

**Expected behavior**
A payout to the ctez vault would be expected.

**Environment**
 - Source Code Build
 - Chain mainnet (Hangzhou)
 - actual command used: `python3 src/main.py -C 422 -P tzkt -M 3 -O 60 -V on -D`
 - Operating system: macOS Monterey

**Additional context**
Is the gas fee estimation due to the protocol upgrade broken?

**Comment by dansan566** [comment]
We found the issue! Most of the time, the authorized depositor is not the baker but rather the payout address. I've already created an issue within the ctez app. However, I think we need to better catch the runtime error! 

https://github.com/Tezsure/ctez/issues/106

**Comment by baketzforme** [comment]
I'm not sure there's a way for Tezsure/ctez to fix this now that contracts exist in the wild.

I don't know how feasible this is, but a potential workaround on TRD's end would be if TRD encounters a simulation error for a payment to a KT1 address, maybe it can then check the address of the contract admin and if it is the ctez Admin (`KT1GWnsoFZVHGh7roXEER3qeCcgJgrXT3de2`) then the payment is just made to the owner (`tz1...`) address instead.

**Comment by jdsika** [comment]
They have adjusted the frontent. I think we still can at least give out a proper warning or at best do the redirect.
