### ISSUE TITLE
Slack Invite not working

### ISSUE THREAD

**Issue by DicksonWu654** [tezos-reward-distributor-organization/tezos-reward-distributor#535]
**Describe the bug**
Hi - the slack invite in the readme doesn't work - it expects me to have an account already in the channel
<img width="505" alt="Screen Shot 2021-12-28 at 2 09 48 AM" src="https://user-images.githubusercontent.com/33645481/147538604-77b0e212-3351-4251-9d60-adf47f2d77d1.png">
<img width="543" alt="Screen Shot 2021-12-28 at 2 10 03 AM" src="https://user-images.githubusercontent.com/33645481/147538632-21091e9b-7ca1-40f4-b870-776199d3557a.png">

**Comment by jdsika** [comment]
Thank you for reporting. Apparently I cannot create "invite links" but I have contacted the admins of the baking slack to find a solution
