### ISSUE TITLE
Write an how-to about testing

### ISSUE THREAD

**Issue by chiptus** [tezos-reward-distributor-organization/tezos-reward-distributor#537]
It would be easier to fix and reproduce bugs if we can easily test. according to @jdsika there's an infrastructure for unit testing.

@vkresch (by request from @jdsika ) please write a document about unit testing :pray:

**Comment by vkresch** [comment]
@chiptus the documentation for the tests you can find [here](https://tezos-reward-distributor-organization.github.io/tezos-reward-distributor/testing.html). To run the test you need to have [pytest](https://pypi.org/project/pytest/) installed and the python path variable defined with `export PYTHONPATH=$PYTHONPATH:$(pwd)/src` and then run `pytest tests` or `python -m pytest tests`.

**Comment by jdsika** [comment]
@chiptus could you see if these instructions in #578 are sufficient for you?
