### ISSUE TITLE
Bug: Does this ever return something else then true?!

### ISSUE THREAD

**Issue by jdsika** [tezos-reward-distributor-organization/tezos-reward-distributor#551]
https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/blob/1446f36d783df6721dd2e9d2f7ee32cdeac3b476/src/main.py#L14

**Comment by jdsika** [comment]
More like this:

```
def installed(package):
    if hasattr(pip, 'main'):
        code = pip.main(['install', package])
    else:
        code = pip._internal.main(['install', package])
    if code != 0:
        return False
    else:
        return True
```

**Comment by vkresch** [comment]
@jdsika please open a PR if you already have an implementation in mind to run tests on it.

**Comment by jdsika** [comment]
yeah, I was so suprised by that and couldn't really believe this stupid bug lol
I found it "by accident" - currently working on another project. Will commit tomorrow. Maybe you can help me with the unit tests. I am still not very good at that. Mostly trouble setting up my VS Code environment...

**Comment by ericlavoie** [comment]
Damn I did not know of this hasattr function, I could have used it in my plugin fix, it's simpler.

**Comment by jdsika** [comment]
Need to run. Forgot black formatting
