### ISSUE TITLE
Delay payment at start of cycle

### ISSUE THREAD

**Issue by darrensteele** [tezos-reward-distributor-organization/tezos-reward-distributor#561]
The start of the cycle tends to be a bit chaotic with all the bakers trying to make payments in the first block.  Can we have a config along the lines of:
payment_delay_blocks : 12

Which in this case would only start trying to make the batch transfers after 12 blocks have occurred [ 6 minutes with the current protocol ].

Hopefully that might lead to a reduction in the number of backtracks that occur,

**Comment by Pea-skillz** [comment]
Hello,

I think the option `--payment_offset` is what you need no ?
```
-O PAYMENT_OFFSET, --payment_offset PAYMENT_OFFSET
 Number of blocks to wait after a cycle starts before starting payments. This can be useful because cycle beginnings may be busy.
```

**Comment by darrensteele** [comment]
Ah cool. How did I miss that!
