### ISSUE TITLE
Installing requirements causes and error with the latest tweepy 4.7.0

### ISSUE THREAD

**Issue by EMES77** [tezos-reward-distributor-organization/tezos-reward-distributor#574]
**Describe the bug**
I installed TRD from scratch because i had a very old version running.
When running requirements.txt i got the error `tweepy 4.7.0 has requirement requests<3,>=2.27.0, but you'll have requests 2.21.0 which is incompatible`
I solved this locally by changing the first row in requirements.txt from `requests>=2.20.0` to `requests>=2.27.0`. After that no error message occured and i could start TRD as usual.
I'd change it myself and make a pull request but i don't know how (yet)

Running on Raspberry Pi 64bit. No docker.

**Comment by jdsika** [comment]
Look at the developer section I try a PR. Thank you for the report! A very good start 🙂

**Comment by ericlavoie** [comment]
Good catch. thanks

**Comment by EMES77** [comment]
I looked at the PR. I understand just little but I'll try my best to test.

**Comment by ericlavoie** [comment]
I created the PR
