### ISSUE TITLE
why does TRD check its python dependencies at start time?

### ISSUE THREAD

**Issue by nicolasochem** [tezos-reward-distributor-organization/tezos-reward-distributor#595]
I don't know of any other python tool that does this. Is there a better way perhaps?

**Comment by vkresch** [comment]
This is just to make sure that all dependencies are installed before running trd and realizing on run time, e.g. during the payout, that for example a plugin dependency is not installed thus throwing an ugly exception.

**Comment by utdrmac** [comment]
Because people don't read instructions, and instead of having issue after issue after slack message after slack message asking "why isn't it working" sometimes it is easier to just do it for the user.
