### ISSUE TITLE
Calculation report addresses excluded by configuration accounting

### ISSUE THREAD

**Issue by songproducer** [tezos-reward-distributor-organization/tezos-reward-distributor#601]
**Is your feature request related to a problem? Please describe.**
I'm trying to account for the income going to my baker from a vault I've excluded in the configuration file.

**Describe the solution you'd like**
An extra column for amount that shows that cycle's income

**Comment by jdsika** [comment]
I suggest to use the calculation files for accounting. At least that's what I am doing :)

Feel free to reopen if you think this is not a aolution.
