### ISSUE TITLE
Support for Jakartanet

### ISSUE THREAD

**Issue by brantje** [tezos-reward-distributor-organization/tezos-reward-distributor#606]
**Is your feature request related to a problem? Please describe.**
Currently when TRD is started with --network=JAKARTANET it errors

**Describe the solution you'd like**

TRD should run on Jakartanet

**Describe alternatives you've considered**

-
**Additional context**

-

**Comment by jdsika** [comment]
If you do --help it will tell you what the name of the supported testnet is. With the creation of "ghostnet" we also refer in TRD only to "ghostnet". This network is currently running jakarta which means TRD should support it as well. Do you have any issues running TRD with Ghostnet?

**Comment by rvermootenct** [comment]
@brantje,  I am closing this issue. If you think this is still an issue please reopen.
