### ISSUE TITLE
Problem with using the new addresses as owner and founder.

### ISSUE THREAD

**Issue by Nikolay-everstake** [tezos-reward-distributor-organization/tezos-reward-distributor#659]
We created TRD config where we use who new addresses as owner and founder.
Our config is
version : 1.0
baking_address : tz1aRoaRhSpRYvFdyvgWLL6TGyRoGF51wDjM
payment_address : tz1W1en9UpMCH4ZJL8wQCh8JDKCZARyVx2co
service_fee : 15
founders_map : {tz1UD66sDxg8zsfLYQpKu7568zBHksxhExLh : 1}
owners_map : {tz1arGrL4EZtJjtJQka425jAZ3BELCHh6cuz : 1}
specials_map : {}
supporters_set : {}
min_delegation_amt : 0
delegator_pays_xfer_fee : false
reactivate_zeroed: false
delegator_pays_ra_fee: false
pay_denunciation_rewards: false
rules_map:
Both of these addresses is revealed:
https://tzkt.io/oo4dfSv7jkmd1U5Wij6NhKjnVMx9hGJP2aiR6dkB3ogfagfenUj/97030664
https://tzkt.io/ooyMRFsziuz3oCe68dpdenK67wcb65N1dfHXkUxi1eiR1nXs2wH/97030628
But when we executed --Dry-Run we got this error:
tz1UD66sDxg8zsfLYQpKu7568zBHksxhExLh,F,2583512569,None,undefined,Excluded by zero balance.
tz1arGrL4EZtJjtJQka425jAZ3BELCHh6cuz,O,2204958652,None,undefined,Excluded by zero balance.
We propose a bounty of $100 for resolving this issue

**Comment by jdsika** [comment]
ok, so we have a few things:
- [x]  Addresses are revealed
- [x] Address has balance > 0
Let's see

**Comment by jdsika** [comment]
I am guessing it is because the delegation status is not yet active. It is definitely a bug. Thank you for reporting

**Comment by jdsika** [comment]
@Nikolay-everstake could you check if it is the easy fix in the related PR? Please still use dry-run

**Comment by jdsika** [comment]
@Nikolay-everstake I am sorry your config is totally fine!!!! I did do a typo! I just meant "it has something to do with the value FALSE"

Please remove the config element and leave it as before :)

git pull

and try again

**Comment by Nikolay-everstake** [comment]
See this in logs
tz1UD66sDxg8zsfLYQpKu7568zBHksxhExLh,F,2583512569,None,done,Empty account needed reactivation.
tz1arGrL4EZtJjtJQka425jAZ3BELCHh6cuz,O,2204958652,None,done,Empty account needed reactivation.

**Comment by Nikolay-everstake** [comment]
Is it necessary to stake to baker address from this address or it can be just revealed address?

**Comment by jdsika** [comment]
At least NOW is tries to reactivate it :) I think it is not a problem to run it. I will investigate why the balance is zero. In this case I think you will only pay the reactivation fee

**Comment by jdsika** [comment]
The problem seems to also come from the fact that the address was (at the time) not delegated to the same baker which seemed to have skipped filling out the balance information.
