### ISSUE TITLE
 add the ability to include in the list of those who will not receive a reward, which will be shared between the other delegates

### ISSUE THREAD

**Issue by goodpen** [tezos-reward-distributor-organization/tezos-reward-distributor#8]
add the ability to include in the list of those who will not receive a reward, which will be shared between the other delegates

**Comment by habanoz** [comment]
I added BusinessConfigX.py to include excluded_delegators_set. The new file is required to save users from conflicts.

Delegators found in excluded_delegators_set are excluded from reward calculations. All rewards are distributed to remaining delegators. 

I am closing this issue. If you catch any errors, you may open it again.

**Comment by dansan566** [comment]
This issue must be reopened. We are working with excluded_delegators_set but they are currently displayed as payable=1 and receive a reward. The correct value would be payable=0 (along with fee_ratio = 0 ; amount = 0 ; fee_amount = 0 ; fee_rate = 0 ; skipped = 1  and atphase = 1) with a description "excluded by delegators set".

**Comment by jdsika** [comment]
@dansan566 and @amzid 

> All rewards are distributed to remaining delegators.

This is somehow up to debate for me. If a baker excludes an address the rewards should either be shared or be contributed to a specific address?

**Comment by habanoz** [comment]
What is the issue we have here? We have TOB, TOE and TOF options for those excluded. Also we have the ability to specify a specific address?. Is not it enough? If not what else is needed?

**Comment by habanoz** [comment]
https://github.com/habanoz/tezos-reward-distributor/blob/master/examples/tz1boot1pK9h2BVGXdyvfQSv8kd1LQM6H889.yaml

Please have a look at available options. excluded_delegators_set  is no longer used.

See my previous message.

**Comment by jdsika** [comment]
It is resolved - I forgot to close it after your reply.
