### ISSUE TITLE
Load email.ini and fee.ini from the default payment/cfg/ directory

### ISSUE THREAD

**Issue by nurikabe** [tezos-reward-distributor-organization/tezos-reward-distributor#84]
**Is your feature request related to a problem? Please describe.**
Having the .ini files live in the same directory as the repository code makes switching between versions a bit error prone.

**Describe the solution you'd like**
Load email.ini and fee.ini from the default payment/cfg/ directory if they exist there, otherwise fall back to current directory.

**Comment by habanoz** [comment]
Could you please describe errors you got? 
email.ini is not under version control. It is created by the application thus version upgrades should not effect it, or does it?

**Comment by nurikabe** [comment]
Not errors per se.. just a minor nuisance.  Whenever a new version comes out I clone it to a new directory.  When I do this I always forget to copy the `.ini` files.

Would be nice if the .ini files lived in the same directory as the other config files so I didn't have to think about this when doing an upgrade.

**Comment by habanoz** [comment]
I hear you.

**Comment by jdsika** [comment]
The problem I see here is the need to check the compatibility of a configuration file with a specific version of the TRD. Is the version number with which the config was created part onf the .ini? Otherwise would the need to copy it manually be at least a last resort against "forgetting to check if the .ini works with the new TRD version".
We should think about this issue and come up with a solution for the next release.

**Comment by habanoz** [comment]
From a consistency perspective, email.ini and fee.ini should be in the same directory as other configuration files.  Code and config separation is another concern supporting this request. 

> Load email.ini and fee.ini from the default payment/cfg/ directory if they exist there, otherwise fall back to current directory.
The recommended approach is reasonable.

@jdsika 
> The problem I see here is the need to check the compatibility of a configuration file with a specific version of the TRD
email and fee ini files do not have a version association. I am not sure whether adding version information is helpful. Please comment if I am missing anything.

**Comment by habanoz** [comment]
email.ini is not used anymore. fee.ini depends on the tezos version and should remain as a part of the TRD source.
